/**
 * Generate a new BetterAuth schema migration as a golang-migrate file.
 *
 * Runs against the LOCAL auth database after all existing migrations have
 * been applied. BetterAuth's Kysely adapter introspects the live schema and
 * `compileMigrations()` returns SQL for the delta between what's there and
 * what the current `auth.ts` config requires. That delta is written to
 * `database/migrations/auth/NNNNNN_<name>.up.sql`, wrapped in a transaction
 * with `SET LOCAL search_path = auth, public;`.
 *
 * The generator refuses to run unless `auth.schema_migrations.version`
 * matches the highest migration number on disk; otherwise the generated
 * delta would conflict with un-applied prior migrations.
 *
 * Down migrations are written as a TODO stub: BetterAuth does not generate
 * reverse SQL.
 */
import { mkdirSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getMigrations } from "better-auth/db/migration";
import { auth } from "../src/auth.js";
import { pool } from "../src/env.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const migrationsDir = resolve(repoRoot, "database", "migrations", "auth");

function nextMigrationNumber(): number {
  if (!existsSync(migrationsDir)) {
    return 1;
  }
  const files = readdirSync(migrationsDir).filter((f) =>
    /^\d{6}_.*\.up\.sql$/.test(f),
  );
  if (files.length === 0) {
    return 1;
  }
  const max = files
    .map((f) => parseInt(f.slice(0, 6), 10))
    .reduce((a, b) => Math.max(a, b), 0);
  return max + 1;
}

function pad(n: number, width = 6): string {
  return n.toString().padStart(width, "0");
}

function maxOnDiskVersion(): number {
  if (!existsSync(migrationsDir)) {
    return 0;
  }
  const versions = readdirSync(migrationsDir)
    .filter((f) => /^\d{6}_.*\.up\.sql$/.test(f))
    .map((f) => parseInt(f.slice(0, 6), 10));
  return versions.length ? Math.max(...versions) : 0;
}

async function assertSchemaUpToDate(): Promise<void> {
  const exists = await pool.query<{ exists: boolean }>(
    `SELECT EXISTS (
       SELECT 1 FROM information_schema.tables
       WHERE table_schema = 'auth' AND table_name = 'schema_migrations'
     ) AS exists`,
  );
  if (!exists.rows[0]?.exists) {
    console.error(
      "auth schema is not initialized. apply existing migrations first:\n" +
        "  mise run migrate:auth",
    );
    process.exit(1);
  }

  const applied = await pool.query<{ version: string | null }>(
    `SELECT MAX(version)::text AS version
       FROM auth.schema_migrations
      WHERE NOT dirty`,
  );
  const appliedVersion = parseInt(applied.rows[0]?.version ?? "0", 10);
  const onDisk = maxOnDiskVersion();

  if (appliedVersion < onDisk) {
    console.error(
      `auth schema is at version ${appliedVersion} but ${onDisk} migrations exist on disk.\n` +
        "apply pending migrations first:\n" +
        "  mise run migrate:auth",
    );
    process.exit(1);
  }
}

async function main() {
  const name = process.argv[2];
  if (!name || !/^[a-z0-9_]+$/.test(name)) {
    console.error("usage: generate-migration <name>");
    console.error("       name must be lowercase snake_case");
    process.exit(2);
  }

  await assertSchemaUpToDate();

  const { compileMigrations } = await getMigrations(auth.options);
  const migrationSql = (await compileMigrations()).trim();

  // BetterAuth returns a bare ";" when there is nothing to migrate. Treat
  // any output that has no real DDL (only whitespace and semicolons) as a
  // no-op rather than writing an empty migration file.
  if (!migrationSql.replace(/[;\s]/g, "")) {
    console.log("no schema changes detected; nothing to generate.");
    await pool.end();
    return;
  }

  const seq = nextMigrationNumber();
  const upPath = resolve(migrationsDir, `${pad(seq)}_${name}.up.sql`);
  const downPath = resolve(migrationsDir, `${pad(seq)}_${name}.down.sql`);

  mkdirSync(migrationsDir, { recursive: true });

  const header =
    `-- BetterAuth schema migration (generated by auth/scripts/generate-migration.ts).\n` +
    `--\n` +
    `-- Do not edit by hand: regenerate by running \`mise run auth:migration <name>\`\n` +
    `-- after changing auth/src/auth.ts (plugins, fields, etc.).\n\n` +
    `BEGIN;\n\n` +
    `SET LOCAL search_path = auth, public;\n\n`;

  const footer = `\n\nCOMMIT;\n`;

  writeFileSync(upPath, header + migrationSql + footer);
  writeFileSync(
    downPath,
    `-- TODO: BetterAuth does not generate reverse migrations.\n` +
      `-- Hand-edit if a real rollback is required; otherwise reset the auth\n` +
      `-- schema by running \`DROP SCHEMA auth CASCADE\` and reapplying from 1.\n`,
  );

  console.log(`wrote ${upPath}`);
  console.log(`wrote ${downPath} (TODO stub)`);

  await pool.end();
}

main().catch((err) => {
  console.error("generation failed:", err);
  process.exitCode = 1;
});
