// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityExplanation = `-- name: CreateActivityExplanation :one
INSERT INTO activity_explanations (camp_id, solution_id, counselor_id, explanation_type, constraint_name, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, solution_id, counselor_id, explanation_type, constraint_name, message
`

type CreateActivityExplanationParams struct {
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

func (q *Queries) CreateActivityExplanation(ctx context.Context, arg CreateActivityExplanationParams) (ActivityExplanation, error) {
	row := q.db.QueryRow(ctx, createActivityExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Message,
	)
	var i ActivityExplanation
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Message,
	)
	return i, err
}

const listActivityExplanationsBySolution = `-- name: ListActivityExplanationsBySolution :many
SELECT id, camp_id, solution_id, counselor_id, explanation_type, constraint_name, message
FROM activity_explanations
WHERE solution_id = $1 AND camp_id = $2
ORDER BY counselor_id, explanation_type, message
`

type ListActivityExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListActivityExplanationsBySolution(ctx context.Context, arg ListActivityExplanationsBySolutionParams) ([]ActivityExplanation, error) {
	rows, err := q.db.Query(ctx, listActivityExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityExplanation
	for rows.Next() {
		var i ActivityExplanation
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
