// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_solutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivitySolution = `-- name: CreateActivitySolution :one
INSERT INTO activity_solutions (camp_id, assignment_run_id, solution_index, score, score_breakdown)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, assignment_run_id, solution_index, score, score_breakdown
`

type CreateActivitySolutionParams struct {
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

func (q *Queries) CreateActivitySolution(ctx context.Context, arg CreateActivitySolutionParams) (ActivitySolution, error) {
	row := q.db.QueryRow(ctx, createActivitySolution,
		arg.CampID,
		arg.AssignmentRunID,
		arg.SolutionIndex,
		arg.Score,
		arg.ScoreBreakdown,
	)
	var i ActivitySolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getActivitySolution = `-- name: GetActivitySolution :one
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM activity_solutions
WHERE id = $1 AND camp_id = $2 AND assignment_run_id = $3
`

type GetActivitySolutionParams struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
}

func (q *Queries) GetActivitySolution(ctx context.Context, arg GetActivitySolutionParams) (ActivitySolution, error) {
	row := q.db.QueryRow(ctx, getActivitySolution, arg.ID, arg.CampID, arg.AssignmentRunID)
	var i ActivitySolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const listActivitySolutionsByRun = `-- name: ListActivitySolutionsByRun :many
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM activity_solutions
WHERE assignment_run_id = $1 AND camp_id = $2
ORDER BY solution_index
`

type ListActivitySolutionsByRunParams struct {
	AssignmentRunID pgtype.UUID
	CampID          pgtype.UUID
}

func (q *Queries) ListActivitySolutionsByRun(ctx context.Context, arg ListActivitySolutionsByRunParams) ([]ActivitySolution, error) {
	rows, err := q.db.Query(ctx, listActivitySolutionsByRun, arg.AssignmentRunID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivitySolution
	for rows.Next() {
		var i ActivitySolution
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AssignmentRunID,
			&i.SolutionIndex,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
