// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityAssignment = `-- name: CreateActivityAssignment :one
INSERT INTO activity_assignments (camp_id, solution_id, counselor_id, session_activity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, counselor_id, session_activity_id
`

type CreateActivityAssignmentParams struct {
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
}

func (q *Queries) CreateActivityAssignment(ctx context.Context, arg CreateActivityAssignmentParams) (ActivityAssignment, error) {
	row := q.db.QueryRow(ctx, createActivityAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.SessionActivityID,
	)
	var i ActivityAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.SessionActivityID,
	)
	return i, err
}

const listActivityAssignmentsBySolution = `-- name: ListActivityAssignmentsBySolution :many
SELECT a.id, a.camp_id, a.solution_id, a.counselor_id, a.session_activity_id,
       co.counselor_name AS counselor_name,
       act.activity_name AS activity_name,
       ts.time_slot_name AS time_slot_name,
       sts.sort_order AS sort_order
FROM activity_assignments a
JOIN counselors co ON co.id = a.counselor_id
JOIN session_activities sa ON sa.id = a.session_activity_id
JOIN activities act ON act.id = sa.activity_id
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
JOIN time_slots ts ON ts.id = sts.time_slot_id
WHERE a.solution_id = $1 AND a.camp_id = $2
ORDER BY sts.sort_order, sts.id, act.activity_name, co.counselor_name
`

type ListActivityAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListActivityAssignmentsBySolutionRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
	CounselorName     string
	ActivityName      string
	TimeSlotName      string
	SortOrder         int32
}

func (q *Queries) ListActivityAssignmentsBySolution(ctx context.Context, arg ListActivityAssignmentsBySolutionParams) ([]ListActivityAssignmentsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listActivityAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityAssignmentsBySolutionRow
	for rows.Next() {
		var i ListActivityAssignmentsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.SessionActivityID,
			&i.CounselorName,
			&i.ActivityName,
			&i.TimeSlotName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
