// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityAssignment = `-- name: CreateActivityAssignment :one
INSERT INTO activity_assignments (camp_id, solution_id, counselor_id, session_activity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, counselor_id, session_activity_id
`

type CreateActivityAssignmentParams struct {
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
}

func (q *Queries) CreateActivityAssignment(ctx context.Context, arg CreateActivityAssignmentParams) (ActivityAssignment, error) {
	row := q.db.QueryRow(ctx, createActivityAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.SessionActivityID,
	)
	var i ActivityAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.SessionActivityID,
	)
	return i, err
}

const listActivityAssignmentsBySolution = `-- name: ListActivityAssignmentsBySolution :many
SELECT id, camp_id, solution_id, counselor_id, session_activity_id
FROM activity_assignments
WHERE solution_id = $1 AND camp_id = $2
ORDER BY session_activity_id, counselor_id
`

type ListActivityAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListActivityAssignmentsBySolution(ctx context.Context, arg ListActivityAssignmentsBySolutionParams) ([]ActivityAssignment, error) {
	rows, err := q.db.Query(ctx, listActivityAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityAssignment
	for rows.Next() {
		var i ActivityAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.SessionActivityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
