// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (camp_id, activity_name)
VALUES ($1, $2)
RETURNING id, camp_id, activity_name, archived
`

type CreateActivityParams struct {
	CampID       pgtype.UUID
	ActivityName string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity, arg.CampID, arg.ActivityName)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.ActivityName,
		&i.Archived,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities
WHERE id = $1 AND camp_id = $2
`

type DeleteActivityParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivity = `-- name: GetActivity :one
SELECT id, camp_id, activity_name, archived
FROM activities
WHERE id = $1 AND camp_id = $2
`

type GetActivityParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, arg.ID, arg.CampID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.ActivityName,
		&i.Archived,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, camp_id, activity_name, archived
FROM activities
WHERE camp_id = $1 AND archived = false
ORDER BY activity_name
`

func (q *Queries) ListActivities(ctx context.Context, campID pgtype.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivities, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.ActivityName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivities = `-- name: ListAllActivities :many
SELECT id, camp_id, activity_name, archived
FROM activities
WHERE camp_id = $1
ORDER BY activity_name
`

func (q *Queries) ListAllActivities(ctx context.Context, campID pgtype.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivities, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.ActivityName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedActivities = `-- name: ListArchivedActivities :many
SELECT id, camp_id, activity_name, archived
FROM activities
WHERE camp_id = $1 AND archived = true
ORDER BY activity_name
`

func (q *Queries) ListArchivedActivities(ctx context.Context, campID pgtype.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listArchivedActivities, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.ActivityName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET activity_name = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, activity_name, archived
`

type UpdateActivityParams struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	ActivityName string
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity, arg.ID, arg.CampID, arg.ActivityName)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.ActivityName,
		&i.Archived,
	)
	return i, err
}
