// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_certifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityCertification = `-- name: CreateActivityCertification :one
INSERT INTO activity_certifications (camp_id, activity_id, certification_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, activity_id, certification_id
`

type CreateActivityCertificationParams struct {
	CampID          pgtype.UUID
	ActivityID      pgtype.UUID
	CertificationID pgtype.UUID
}

func (q *Queries) CreateActivityCertification(ctx context.Context, arg CreateActivityCertificationParams) (ActivityCertification, error) {
	row := q.db.QueryRow(ctx, createActivityCertification, arg.CampID, arg.ActivityID, arg.CertificationID)
	var i ActivityCertification
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.ActivityID,
		&i.CertificationID,
	)
	return i, err
}

const deleteActivityCertification = `-- name: DeleteActivityCertification :execrows
DELETE FROM activity_certifications
WHERE id = $1 AND camp_id = $2 AND activity_id = $3
`

type DeleteActivityCertificationParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	ActivityID pgtype.UUID
}

func (q *Queries) DeleteActivityCertification(ctx context.Context, arg DeleteActivityCertificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityCertification, arg.ID, arg.CampID, arg.ActivityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivityCertifications = `-- name: ListActivityCertifications :many
SELECT ac.id, ac.camp_id, ac.activity_id, ac.certification_id, c.certification_name
FROM activity_certifications ac
JOIN certifications c ON c.id = ac.certification_id
WHERE ac.activity_id = $1 AND ac.camp_id = $2
ORDER BY c.certification_name
`

type ListActivityCertificationsParams struct {
	ActivityID pgtype.UUID
	CampID     pgtype.UUID
}

type ListActivityCertificationsRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	ActivityID        pgtype.UUID
	CertificationID   pgtype.UUID
	CertificationName string
}

func (q *Queries) ListActivityCertifications(ctx context.Context, arg ListActivityCertificationsParams) ([]ListActivityCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listActivityCertifications, arg.ActivityID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityCertificationsRow
	for rows.Next() {
		var i ListActivityCertificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.ActivityID,
			&i.CertificationID,
			&i.CertificationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
