// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: age_groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgeGroup = `-- name: CreateAgeGroup :one
INSERT INTO age_groups (camp_id, age_group_name)
VALUES ($1, $2)
RETURNING id, camp_id, age_group_name, archived
`

type CreateAgeGroupParams struct {
	CampID       pgtype.UUID
	AgeGroupName string
}

func (q *Queries) CreateAgeGroup(ctx context.Context, arg CreateAgeGroupParams) (AgeGroup, error) {
	row := q.db.QueryRow(ctx, createAgeGroup, arg.CampID, arg.AgeGroupName)
	var i AgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupName,
		&i.Archived,
	)
	return i, err
}

const deleteAgeGroup = `-- name: DeleteAgeGroup :execrows
DELETE FROM age_groups
WHERE id = $1 AND camp_id = $2
`

type DeleteAgeGroupParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteAgeGroup(ctx context.Context, arg DeleteAgeGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgeGroup, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgeGroup = `-- name: GetAgeGroup :one
SELECT id, camp_id, age_group_name, archived
FROM age_groups
WHERE id = $1 AND camp_id = $2
`

type GetAgeGroupParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetAgeGroup(ctx context.Context, arg GetAgeGroupParams) (AgeGroup, error) {
	row := q.db.QueryRow(ctx, getAgeGroup, arg.ID, arg.CampID)
	var i AgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupName,
		&i.Archived,
	)
	return i, err
}

const listAgeGroups = `-- name: ListAgeGroups :many
SELECT id, camp_id, age_group_name, archived
FROM age_groups
WHERE camp_id = $1 AND archived = false
ORDER BY age_group_name
`

func (q *Queries) ListAgeGroups(ctx context.Context, campID pgtype.UUID) ([]AgeGroup, error) {
	rows, err := q.db.Query(ctx, listAgeGroups, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgeGroup
	for rows.Next() {
		var i AgeGroup
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AgeGroupName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgeGroups = `-- name: ListAllAgeGroups :many
SELECT id, camp_id, age_group_name, archived
FROM age_groups
WHERE camp_id = $1
ORDER BY age_group_name
`

func (q *Queries) ListAllAgeGroups(ctx context.Context, campID pgtype.UUID) ([]AgeGroup, error) {
	rows, err := q.db.Query(ctx, listAllAgeGroups, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgeGroup
	for rows.Next() {
		var i AgeGroup
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AgeGroupName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedAgeGroups = `-- name: ListArchivedAgeGroups :many
SELECT id, camp_id, age_group_name, archived
FROM age_groups
WHERE camp_id = $1 AND archived = true
ORDER BY age_group_name
`

func (q *Queries) ListArchivedAgeGroups(ctx context.Context, campID pgtype.UUID) ([]AgeGroup, error) {
	rows, err := q.db.Query(ctx, listArchivedAgeGroups, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgeGroup
	for rows.Next() {
		var i AgeGroup
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AgeGroupName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgeGroup = `-- name: UpdateAgeGroup :one
UPDATE age_groups
SET age_group_name = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, age_group_name, archived
`

type UpdateAgeGroupParams struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	AgeGroupName string
}

func (q *Queries) UpdateAgeGroup(ctx context.Context, arg UpdateAgeGroupParams) (AgeGroup, error) {
	row := q.db.QueryRow(ctx, updateAgeGroup, arg.ID, arg.CampID, arg.AgeGroupName)
	var i AgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupName,
		&i.Archived,
	)
	return i, err
}
