// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignmentRun = `-- name: CreateAssignmentRun :one
INSERT INTO assignment_runs (camp_id, session_id, run_type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, run_type, status, created_at, is_stale
`

type CreateAssignmentRunParams struct {
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
	Status    string
}

func (q *Queries) CreateAssignmentRun(ctx context.Context, arg CreateAssignmentRunParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, createAssignmentRun,
		arg.CampID,
		arg.SessionID,
		arg.RunType,
		arg.Status,
	)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
		&i.IsStale,
	)
	return i, err
}

const deleteAssignmentRun = `-- name: DeleteAssignmentRun :execrows
DELETE FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type DeleteAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteAssignmentRun(ctx context.Context, arg DeleteAssignmentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignmentRun, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAssignmentRunsBySessionAndType = `-- name: DeleteAssignmentRunsBySessionAndType :execrows
DELETE FROM assignment_runs
WHERE camp_id = $1 AND session_id = $2 AND run_type = $3
`

type DeleteAssignmentRunsBySessionAndTypeParams struct {
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
}

func (q *Queries) DeleteAssignmentRunsBySessionAndType(ctx context.Context, arg DeleteAssignmentRunsBySessionAndTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignmentRunsBySessionAndType, arg.CampID, arg.SessionID, arg.RunType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssignmentRun = `-- name: GetAssignmentRun :one
SELECT id, camp_id, session_id, run_type, status, created_at, is_stale
FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type GetAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetAssignmentRun(ctx context.Context, arg GetAssignmentRunParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, getAssignmentRun, arg.ID, arg.CampID)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
		&i.IsStale,
	)
	return i, err
}

const listAssignmentRunsBySession = `-- name: ListAssignmentRunsBySession :many
SELECT
    ar.id,
    ar.camp_id,
    ar.session_id,
    ar.run_type,
    ar.status,
    ar.created_at,
    ar.is_stale,
    arss.solution_id AS selected_solution_id
FROM assignment_runs ar
LEFT JOIN assignment_run_selected_solutions arss ON arss.run_id = ar.id AND arss.camp_id = ar.camp_id
WHERE ar.session_id = $1 AND ar.camp_id = $2
ORDER BY ar.created_at DESC
`

type ListAssignmentRunsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListAssignmentRunsBySessionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	CreatedAt          pgtype.Timestamptz
	IsStale            bool
	SelectedSolutionID pgtype.UUID
}

func (q *Queries) ListAssignmentRunsBySession(ctx context.Context, arg ListAssignmentRunsBySessionParams) ([]ListAssignmentRunsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentRunsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentRunsBySessionRow
	for rows.Next() {
		var i ListAssignmentRunsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.RunType,
			&i.Status,
			&i.CreatedAt,
			&i.IsStale,
			&i.SelectedSolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPreviousSession = `-- name: ListSessionsByPreviousSession :many
SELECT id
FROM sessions
WHERE camp_id = $1
  AND previous_session = ANY($2::uuid[])
`

type ListSessionsByPreviousSessionParams struct {
	CampID             pgtype.UUID
	PreviousSessionIds []pgtype.UUID
}

func (q *Queries) ListSessionsByPreviousSession(ctx context.Context, arg ListSessionsByPreviousSessionParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionsByPreviousSession, arg.CampID, arg.PreviousSessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAssignmentRunsBySessionAndType = `-- name: LockAssignmentRunsBySessionAndType :many
SELECT id
FROM assignment_runs
WHERE camp_id = $1 AND session_id = $2 AND run_type = $3
ORDER BY id
FOR UPDATE
`

type LockAssignmentRunsBySessionAndTypeParams struct {
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
}

func (q *Queries) LockAssignmentRunsBySessionAndType(ctx context.Context, arg LockAssignmentRunsBySessionAndTypeParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockAssignmentRunsBySessionAndType, arg.CampID, arg.SessionID, arg.RunType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssignmentRunsStale = `-- name: MarkAssignmentRunsStale :execrows
UPDATE assignment_runs
SET is_stale = true
WHERE camp_id = $1
  AND session_id = ANY($2::uuid[])
  AND run_type = ANY($3::text[])
  AND is_stale = false
`

type MarkAssignmentRunsStaleParams struct {
	CampID     pgtype.UUID
	SessionIds []pgtype.UUID
	RunTypes   []string
}

func (q *Queries) MarkAssignmentRunsStale(ctx context.Context, arg MarkAssignmentRunsStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAssignmentRunsStale, arg.CampID, arg.SessionIds, arg.RunTypes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssignmentRunStatus = `-- name: UpdateAssignmentRunStatus :one
UPDATE assignment_runs
SET status = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, session_id, run_type, status, created_at, is_stale
`

type UpdateAssignmentRunStatusParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
	Status string
}

func (q *Queries) UpdateAssignmentRunStatus(ctx context.Context, arg UpdateAssignmentRunStatusParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, updateAssignmentRunStatus, arg.ID, arg.CampID, arg.Status)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
		&i.IsStale,
	)
	return i, err
}
