// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignmentRun = `-- name: CreateAssignmentRun :one
INSERT INTO assignment_runs (camp_id, session_id, run_type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, run_type, status, created_at
`

type CreateAssignmentRunParams struct {
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
	Status    string
}

func (q *Queries) CreateAssignmentRun(ctx context.Context, arg CreateAssignmentRunParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, createAssignmentRun,
		arg.CampID,
		arg.SessionID,
		arg.RunType,
		arg.Status,
	)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssignmentRun = `-- name: DeleteAssignmentRun :execrows
DELETE FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type DeleteAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteAssignmentRun(ctx context.Context, arg DeleteAssignmentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignmentRun, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssignmentRun = `-- name: GetAssignmentRun :one
SELECT id, camp_id, session_id, run_type, status, created_at
FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type GetAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetAssignmentRun(ctx context.Context, arg GetAssignmentRunParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, getAssignmentRun, arg.ID, arg.CampID)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentRunsBySession = `-- name: ListAssignmentRunsBySession :many
SELECT
    ar.id,
    ar.camp_id,
    ar.session_id,
    ar.run_type,
    ar.status,
    ar.created_at,
    arss.solution_id AS selected_solution_id
FROM assignment_runs ar
LEFT JOIN assignment_run_selected_solutions arss ON arss.run_id = ar.id AND arss.camp_id = ar.camp_id
WHERE ar.session_id = $1 AND ar.camp_id = $2
ORDER BY ar.created_at DESC
`

type ListAssignmentRunsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListAssignmentRunsBySessionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	CreatedAt          pgtype.Timestamptz
	SelectedSolutionID pgtype.UUID
}

func (q *Queries) ListAssignmentRunsBySession(ctx context.Context, arg ListAssignmentRunsBySessionParams) ([]ListAssignmentRunsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentRunsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentRunsBySessionRow
	for rows.Next() {
		var i ListAssignmentRunsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.RunType,
			&i.Status,
			&i.CreatedAt,
			&i.SelectedSolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignmentRunStatus = `-- name: UpdateAssignmentRunStatus :one
UPDATE assignment_runs
SET status = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, session_id, run_type, status, created_at
`

type UpdateAssignmentRunStatusParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
	Status string
}

func (q *Queries) UpdateAssignmentRunStatus(ctx context.Context, arg UpdateAssignmentRunStatusParams) (AssignmentRun, error) {
	row := q.db.QueryRow(ctx, updateAssignmentRunStatus, arg.ID, arg.CampID, arg.Status)
	var i AssignmentRun
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
