// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment_run_selected_solutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deselectSolution = `-- name: DeselectSolution :execrows
DELETE FROM assignment_run_selected_solutions
WHERE run_id = $1 AND camp_id = $2
`

type DeselectSolutionParams struct {
	RunID  pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeselectSolution(ctx context.Context, arg DeselectSolutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deselectSolution, arg.RunID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSelectedSolution = `-- name: GetSelectedSolution :one
SELECT camp_id, run_id, solution_id, solution_type
FROM assignment_run_selected_solutions
WHERE run_id = $1 AND camp_id = $2
`

type GetSelectedSolutionParams struct {
	RunID  pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetSelectedSolution(ctx context.Context, arg GetSelectedSolutionParams) (AssignmentRunSelectedSolution, error) {
	row := q.db.QueryRow(ctx, getSelectedSolution, arg.RunID, arg.CampID)
	var i AssignmentRunSelectedSolution
	err := row.Scan(
		&i.CampID,
		&i.RunID,
		&i.SolutionID,
		&i.SolutionType,
	)
	return i, err
}

const selectSolution = `-- name: SelectSolution :one
INSERT INTO assignment_run_selected_solutions (camp_id, run_id, solution_id, solution_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (camp_id, run_id) DO UPDATE
SET solution_id = EXCLUDED.solution_id, solution_type = EXCLUDED.solution_type
RETURNING camp_id, run_id, solution_id, solution_type
`

type SelectSolutionParams struct {
	CampID       pgtype.UUID
	RunID        pgtype.UUID
	SolutionID   pgtype.UUID
	SolutionType string
}

func (q *Queries) SelectSolution(ctx context.Context, arg SelectSolutionParams) (AssignmentRunSelectedSolution, error) {
	row := q.db.QueryRow(ctx, selectSolution,
		arg.CampID,
		arg.RunID,
		arg.SolutionID,
		arg.SolutionType,
	)
	var i AssignmentRunSelectedSolution
	err := row.Scan(
		&i.CampID,
		&i.RunID,
		&i.SolutionID,
		&i.SolutionType,
	)
	return i, err
}
