// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignmentRun = `-- name: CreateAssignmentRun :one
INSERT INTO assignment_runs (camp_id, session_id, run_type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, run_type, status, selected_solution_id, created_at
`

type CreateAssignmentRunParams struct {
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
	Status    string
}

type CreateAssignmentRunRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	SelectedSolutionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateAssignmentRun(ctx context.Context, arg CreateAssignmentRunParams) (CreateAssignmentRunRow, error) {
	row := q.db.QueryRow(ctx, createAssignmentRun,
		arg.CampID,
		arg.SessionID,
		arg.RunType,
		arg.Status,
	)
	var i CreateAssignmentRunRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.SelectedSolutionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssignmentRun = `-- name: DeleteAssignmentRun :execrows
DELETE FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type DeleteAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteAssignmentRun(ctx context.Context, arg DeleteAssignmentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignmentRun, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssignmentRun = `-- name: GetAssignmentRun :one
SELECT id, camp_id, session_id, run_type, status, selected_solution_id, created_at
FROM assignment_runs
WHERE id = $1 AND camp_id = $2
`

type GetAssignmentRunParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

type GetAssignmentRunRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	SelectedSolutionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) GetAssignmentRun(ctx context.Context, arg GetAssignmentRunParams) (GetAssignmentRunRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentRun, arg.ID, arg.CampID)
	var i GetAssignmentRunRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.SelectedSolutionID,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentRunsBySession = `-- name: ListAssignmentRunsBySession :many
SELECT id, camp_id, session_id, run_type, status, selected_solution_id, created_at
FROM assignment_runs
WHERE session_id = $1 AND camp_id = $2
ORDER BY created_at DESC
`

type ListAssignmentRunsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListAssignmentRunsBySessionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	SelectedSolutionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListAssignmentRunsBySession(ctx context.Context, arg ListAssignmentRunsBySessionParams) ([]ListAssignmentRunsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentRunsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentRunsBySessionRow
	for rows.Next() {
		var i ListAssignmentRunsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.RunType,
			&i.Status,
			&i.SelectedSolutionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSolution = `-- name: SelectSolution :one
UPDATE assignment_runs
SET selected_solution_id = $3, status = 'selected'
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, session_id, run_type, status, selected_solution_id, created_at
`

type SelectSolutionParams struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SelectedSolutionID pgtype.UUID
}

type SelectSolutionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	SelectedSolutionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) SelectSolution(ctx context.Context, arg SelectSolutionParams) (SelectSolutionRow, error) {
	row := q.db.QueryRow(ctx, selectSolution, arg.ID, arg.CampID, arg.SelectedSolutionID)
	var i SelectSolutionRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.SelectedSolutionID,
		&i.CreatedAt,
	)
	return i, err
}

const updateAssignmentRunStatus = `-- name: UpdateAssignmentRunStatus :one
UPDATE assignment_runs
SET status = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, session_id, run_type, status, selected_solution_id, created_at
`

type UpdateAssignmentRunStatusParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
	Status string
}

type UpdateAssignmentRunStatusRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	RunType            string
	Status             string
	SelectedSolutionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateAssignmentRunStatus(ctx context.Context, arg UpdateAssignmentRunStatusParams) (UpdateAssignmentRunStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAssignmentRunStatus, arg.ID, arg.CampID, arg.Status)
	var i UpdateAssignmentRunStatusRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.RunType,
		&i.Status,
		&i.SelectedSolutionID,
		&i.CreatedAt,
	)
	return i, err
}
