// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cabins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCabin = `-- name: CreateCabin :one
INSERT INTO cabins (camp_id, age_group_id, cabin_name)
VALUES ($1, $2, $3)
RETURNING id, camp_id, age_group_id, cabin_name
`

type CreateCabinParams struct {
	CampID     pgtype.UUID
	AgeGroupID pgtype.UUID
	CabinName  string
}

func (q *Queries) CreateCabin(ctx context.Context, arg CreateCabinParams) (Cabin, error) {
	row := q.db.QueryRow(ctx, createCabin, arg.CampID, arg.AgeGroupID, arg.CabinName)
	var i Cabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupID,
		&i.CabinName,
	)
	return i, err
}

const deleteCabin = `-- name: DeleteCabin :execrows
DELETE FROM cabins
WHERE id = $1
`

func (q *Queries) DeleteCabin(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCabin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCabin = `-- name: GetCabin :one
SELECT id, camp_id, age_group_id, cabin_name
FROM cabins
WHERE id = $1
`

func (q *Queries) GetCabin(ctx context.Context, id pgtype.UUID) (Cabin, error) {
	row := q.db.QueryRow(ctx, getCabin, id)
	var i Cabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupID,
		&i.CabinName,
	)
	return i, err
}

const listCabins = `-- name: ListCabins :many
SELECT id, camp_id, age_group_id, cabin_name
FROM cabins
WHERE camp_id = $1
ORDER BY cabin_name
`

func (q *Queries) ListCabins(ctx context.Context, campID pgtype.UUID) ([]Cabin, error) {
	rows, err := q.db.Query(ctx, listCabins, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cabin
	for rows.Next() {
		var i Cabin
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AgeGroupID,
			&i.CabinName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCabin = `-- name: UpdateCabin :one
UPDATE cabins
SET age_group_id = $2,
    cabin_name = $3
WHERE id = $1
RETURNING id, camp_id, age_group_id, cabin_name
`

type UpdateCabinParams struct {
	ID         pgtype.UUID
	AgeGroupID pgtype.UUID
	CabinName  string
}

func (q *Queries) UpdateCabin(ctx context.Context, arg UpdateCabinParams) (Cabin, error) {
	row := q.db.QueryRow(ctx, updateCabin, arg.ID, arg.AgeGroupID, arg.CabinName)
	var i Cabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AgeGroupID,
		&i.CabinName,
	)
	return i, err
}
