// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_solutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinSolution = `-- name: CreateCamperCabinSolution :one
INSERT INTO camper_cabin_solutions (camp_id, assignment_run_id, solution_index, score, score_breakdown)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, assignment_run_id, solution_index, score, score_breakdown
`

type CreateCamperCabinSolutionParams struct {
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

func (q *Queries) CreateCamperCabinSolution(ctx context.Context, arg CreateCamperCabinSolutionParams) (CamperCabinSolution, error) {
	row := q.db.QueryRow(ctx, createCamperCabinSolution,
		arg.CampID,
		arg.AssignmentRunID,
		arg.SolutionIndex,
		arg.Score,
		arg.ScoreBreakdown,
	)
	var i CamperCabinSolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getCamperCabinSolution = `-- name: GetCamperCabinSolution :one
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM camper_cabin_solutions
WHERE id = $1 AND camp_id = $2
`

type GetCamperCabinSolutionParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCamperCabinSolution(ctx context.Context, arg GetCamperCabinSolutionParams) (CamperCabinSolution, error) {
	row := q.db.QueryRow(ctx, getCamperCabinSolution, arg.ID, arg.CampID)
	var i CamperCabinSolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const listCamperCabinSolutionsByRun = `-- name: ListCamperCabinSolutionsByRun :many
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM camper_cabin_solutions
WHERE assignment_run_id = $1 AND camp_id = $2
ORDER BY solution_index
`

type ListCamperCabinSolutionsByRunParams struct {
	AssignmentRunID pgtype.UUID
	CampID          pgtype.UUID
}

func (q *Queries) ListCamperCabinSolutionsByRun(ctx context.Context, arg ListCamperCabinSolutionsByRunParams) ([]CamperCabinSolution, error) {
	rows, err := q.db.Query(ctx, listCamperCabinSolutionsByRun, arg.AssignmentRunID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CamperCabinSolution
	for rows.Next() {
		var i CamperCabinSolution
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AssignmentRunID,
			&i.SolutionIndex,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
