// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamp = `-- name: CreateCamp :one
INSERT INTO camps (camp_name, camp_location)
VALUES ($1, $2)
RETURNING id, camp_name, camp_location, camp_enabled
`

type CreateCampParams struct {
	CampName     string
	CampLocation pgtype.Text
}

func (q *Queries) CreateCamp(ctx context.Context, arg CreateCampParams) (Camp, error) {
	row := q.db.QueryRow(ctx, createCamp, arg.CampName, arg.CampLocation)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.CampName,
		&i.CampLocation,
		&i.CampEnabled,
	)
	return i, err
}

const deleteCamp = `-- name: DeleteCamp :execrows
DELETE FROM camps
WHERE id = $1
`

func (q *Queries) DeleteCamp(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCamp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCamp = `-- name: GetCamp :one
SELECT id, camp_name, camp_location, camp_enabled
FROM camps
WHERE id = $1
`

func (q *Queries) GetCamp(ctx context.Context, id pgtype.UUID) (Camp, error) {
	row := q.db.QueryRow(ctx, getCamp, id)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.CampName,
		&i.CampLocation,
		&i.CampEnabled,
	)
	return i, err
}

const listCamps = `-- name: ListCamps :many
SELECT id, camp_name, camp_location, camp_enabled
FROM camps
ORDER BY camp_name
`

func (q *Queries) ListCamps(ctx context.Context) ([]Camp, error) {
	rows, err := q.db.Query(ctx, listCamps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Camp
	for rows.Next() {
		var i Camp
		if err := rows.Scan(
			&i.ID,
			&i.CampName,
			&i.CampLocation,
			&i.CampEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamp = `-- name: UpdateCamp :one
UPDATE camps
SET camp_name = $1,
    camp_location = $2,
    camp_enabled = COALESCE($3, camp_enabled)
WHERE id = $4
RETURNING id, camp_name, camp_location, camp_enabled
`

type UpdateCampParams struct {
	CampName     string
	CampLocation pgtype.Text
	CampEnabled  pgtype.Bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateCamp(ctx context.Context, arg UpdateCampParams) (Camp, error) {
	row := q.db.QueryRow(ctx, updateCamp,
		arg.CampName,
		arg.CampLocation,
		arg.CampEnabled,
		arg.ID,
	)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.CampName,
		&i.CampLocation,
		&i.CampEnabled,
	)
	return i, err
}
