// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamper = `-- name: CreateCamper :one
INSERT INTO campers (camp_id, first_name, last_name, gender)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, first_name, last_name, gender, archived
`

type CreateCamperParams struct {
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
}

type CreateCamperRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) CreateCamper(ctx context.Context, arg CreateCamperParams) (CreateCamperRow, error) {
	row := q.db.QueryRow(ctx, createCamper,
		arg.CampID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
	)
	var i CreateCamperRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Archived,
	)
	return i, err
}

const deleteCamper = `-- name: DeleteCamper :execrows
DELETE FROM campers
WHERE id = $1 AND camp_id = $2
`

type DeleteCamperParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCamper(ctx context.Context, arg DeleteCamperParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCamper, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCamper = `-- name: GetCamper :one
SELECT id, camp_id, first_name, last_name, gender, archived
FROM campers
WHERE id = $1 AND camp_id = $2
`

type GetCamperParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

type GetCamperRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) GetCamper(ctx context.Context, arg GetCamperParams) (GetCamperRow, error) {
	row := q.db.QueryRow(ctx, getCamper, arg.ID, arg.CampID)
	var i GetCamperRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Archived,
	)
	return i, err
}

const listAllCampers = `-- name: ListAllCampers :many
SELECT id, camp_id, first_name, last_name, gender, archived
FROM campers
WHERE camp_id = $1
ORDER BY last_name, first_name
`

type ListAllCampersRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) ListAllCampers(ctx context.Context, campID pgtype.UUID) ([]ListAllCampersRow, error) {
	rows, err := q.db.Query(ctx, listAllCampers, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCampersRow
	for rows.Next() {
		var i ListAllCampersRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedCampers = `-- name: ListArchivedCampers :many
SELECT id, camp_id, first_name, last_name, gender, archived
FROM campers
WHERE camp_id = $1 AND archived = true
ORDER BY last_name, first_name
`

type ListArchivedCampersRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) ListArchivedCampers(ctx context.Context, campID pgtype.UUID) ([]ListArchivedCampersRow, error) {
	rows, err := q.db.Query(ctx, listArchivedCampers, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchivedCampersRow
	for rows.Next() {
		var i ListArchivedCampersRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampers = `-- name: ListCampers :many
SELECT id, camp_id, first_name, last_name, gender, archived
FROM campers
WHERE camp_id = $1 AND archived = false
ORDER BY last_name, first_name
`

type ListCampersRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) ListCampers(ctx context.Context, campID pgtype.UUID) ([]ListCampersRow, error) {
	rows, err := q.db.Query(ctx, listCampers, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampersRow
	for rows.Next() {
		var i ListCampersRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamper = `-- name: UpdateCamper :one
UPDATE campers
SET first_name = $3,
    last_name = $4,
    gender = $5
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, first_name, last_name, gender, archived
`

type UpdateCamperParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
}

type UpdateCamperRow struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	FirstName string
	LastName  string
	Gender    string
	Archived  bool
}

func (q *Queries) UpdateCamper(ctx context.Context, arg UpdateCamperParams) (UpdateCamperRow, error) {
	row := q.db.QueryRow(ctx, updateCamper,
		arg.ID,
		arg.CampID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
	)
	var i UpdateCamperRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Archived,
	)
	return i, err
}
