// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_overrides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinOverride = `-- name: CreateCamperCabinOverride :one
INSERT INTO camper_cabin_overrides (camp_id, session_id, camper_id, session_cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, camper_id, session_cabin_id, created_at
`

type CreateCamperCabinOverrideParams struct {
	CampID         pgtype.UUID
	SessionID      pgtype.UUID
	CamperID       pgtype.UUID
	SessionCabinID pgtype.UUID
}

func (q *Queries) CreateCamperCabinOverride(ctx context.Context, arg CreateCamperCabinOverrideParams) (CamperCabinOverride, error) {
	row := q.db.QueryRow(ctx, createCamperCabinOverride,
		arg.CampID,
		arg.SessionID,
		arg.CamperID,
		arg.SessionCabinID,
	)
	var i CamperCabinOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CamperID,
		&i.SessionCabinID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCamperCabinOverride = `-- name: DeleteCamperCabinOverride :execrows
DELETE FROM camper_cabin_overrides
WHERE id = $1 AND camp_id = $2
`

type DeleteCamperCabinOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCamperCabinOverride(ctx context.Context, arg DeleteCamperCabinOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCamperCabinOverride, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCamperCabinOverride = `-- name: GetCamperCabinOverride :one
SELECT id, camp_id, session_id, camper_id, session_cabin_id, created_at
FROM camper_cabin_overrides
WHERE id = $1 AND camp_id = $2
`

type GetCamperCabinOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCamperCabinOverride(ctx context.Context, arg GetCamperCabinOverrideParams) (CamperCabinOverride, error) {
	row := q.db.QueryRow(ctx, getCamperCabinOverride, arg.ID, arg.CampID)
	var i CamperCabinOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CamperID,
		&i.SessionCabinID,
		&i.CreatedAt,
	)
	return i, err
}

const listCamperCabinOverridesBySession = `-- name: ListCamperCabinOverridesBySession :many
SELECT o.id, o.camp_id, o.session_id, o.camper_id, o.session_cabin_id, o.created_at,
       sagc.cabin_id AS cabin_id,
       cm.first_name AS camper_first_name,
       cm.last_name AS camper_last_name,
       btrim(cm.first_name || ' ' || cm.last_name)::text AS camper_name,
       cb.cabin_name AS cabin_name,
       ag.age_group_name AS age_group_name
FROM camper_cabin_overrides o
JOIN campers cm ON cm.id = o.camper_id
JOIN session_cabins sagc ON sagc.id = o.session_cabin_id
JOIN cabins cb ON cb.id = sagc.cabin_id
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
JOIN age_groups ag ON ag.id = sag.age_group_id
WHERE o.session_id = $1 AND o.camp_id = $2
ORDER BY ag.age_group_name, cb.cabin_name, cm.last_name, cm.first_name
`

type ListCamperCabinOverridesBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCamperCabinOverridesBySessionRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SessionID       pgtype.UUID
	CamperID        pgtype.UUID
	SessionCabinID  pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	CabinID         pgtype.UUID
	CamperFirstName string
	CamperLastName  string
	CamperName      string
	CabinName       string
	AgeGroupName    string
}

func (q *Queries) ListCamperCabinOverridesBySession(ctx context.Context, arg ListCamperCabinOverridesBySessionParams) ([]ListCamperCabinOverridesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listCamperCabinOverridesBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCamperCabinOverridesBySessionRow
	for rows.Next() {
		var i ListCamperCabinOverridesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.CamperID,
			&i.SessionCabinID,
			&i.CreatedAt,
			&i.CabinID,
			&i.CamperFirstName,
			&i.CamperLastName,
			&i.CamperName,
			&i.CabinName,
			&i.AgeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamperCabinOverridesForSolver = `-- name: ListCamperCabinOverridesForSolver :many
SELECT o.camper_id, o.session_cabin_id
FROM camper_cabin_overrides o
WHERE o.session_id = $1 AND o.camp_id = $2
`

type ListCamperCabinOverridesForSolverParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCamperCabinOverridesForSolverRow struct {
	CamperID       pgtype.UUID
	SessionCabinID pgtype.UUID
}

func (q *Queries) ListCamperCabinOverridesForSolver(ctx context.Context, arg ListCamperCabinOverridesForSolverParams) ([]ListCamperCabinOverridesForSolverRow, error) {
	rows, err := q.db.Query(ctx, listCamperCabinOverridesForSolver, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCamperCabinOverridesForSolverRow
	for rows.Next() {
		var i ListCamperCabinOverridesForSolverRow
		if err := rows.Scan(&i.CamperID, &i.SessionCabinID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
