// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamper = `-- name: CreateCamper :one
INSERT INTO campers (camp_id, camper_name, gender)
VALUES ($1, $2, $3)
RETURNING id, camp_id, camper_name, gender
`

type CreateCamperParams struct {
	CampID     pgtype.UUID
	CamperName string
	Gender     string
}

func (q *Queries) CreateCamper(ctx context.Context, arg CreateCamperParams) (Camper, error) {
	row := q.db.QueryRow(ctx, createCamper, arg.CampID, arg.CamperName, arg.Gender)
	var i Camper
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperName,
		&i.Gender,
	)
	return i, err
}

const deleteCamper = `-- name: DeleteCamper :execrows
DELETE FROM campers
WHERE id = $1 AND camp_id = $2
`

type DeleteCamperParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCamper(ctx context.Context, arg DeleteCamperParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCamper, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCamper = `-- name: GetCamper :one
SELECT id, camp_id, camper_name, gender
FROM campers
WHERE id = $1 AND camp_id = $2
`

type GetCamperParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCamper(ctx context.Context, arg GetCamperParams) (Camper, error) {
	row := q.db.QueryRow(ctx, getCamper, arg.ID, arg.CampID)
	var i Camper
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperName,
		&i.Gender,
	)
	return i, err
}

const listCampers = `-- name: ListCampers :many
SELECT id, camp_id, camper_name, gender
FROM campers
WHERE camp_id = $1
ORDER BY camper_name
`

func (q *Queries) ListCampers(ctx context.Context, campID pgtype.UUID) ([]Camper, error) {
	rows, err := q.db.Query(ctx, listCampers, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Camper
	for rows.Next() {
		var i Camper
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CamperName,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamper = `-- name: UpdateCamper :one
UPDATE campers
SET camper_name = $3,
    gender = $4
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, camper_name, gender
`

type UpdateCamperParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	CamperName string
	Gender     string
}

func (q *Queries) UpdateCamper(ctx context.Context, arg UpdateCamperParams) (Camper, error) {
	row := q.db.QueryRow(ctx, updateCamper,
		arg.ID,
		arg.CampID,
		arg.CamperName,
		arg.Gender,
	)
	var i Camper
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperName,
		&i.Gender,
	)
	return i, err
}
