// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinExplanation = `-- name: CreateCamperCabinExplanation :one
INSERT INTO camper_cabin_explanations (camp_id, solution_id, camper_id, explanation_type, constraint_name, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, solution_id, camper_id, explanation_type, constraint_name, message
`

type CreateCamperCabinExplanationParams struct {
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CamperID        pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

func (q *Queries) CreateCamperCabinExplanation(ctx context.Context, arg CreateCamperCabinExplanationParams) (CamperCabinExplanation, error) {
	row := q.db.QueryRow(ctx, createCamperCabinExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CamperID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Message,
	)
	var i CamperCabinExplanation
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CamperID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Message,
	)
	return i, err
}

const listCamperCabinExplanationsBySolution = `-- name: ListCamperCabinExplanationsBySolution :many
SELECT id, camp_id, solution_id, camper_id, explanation_type, constraint_name, message
FROM camper_cabin_explanations
WHERE solution_id = $1 AND camp_id = $2
ORDER BY camper_id, explanation_type
`

type ListCamperCabinExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListCamperCabinExplanationsBySolution(ctx context.Context, arg ListCamperCabinExplanationsBySolutionParams) ([]CamperCabinExplanation, error) {
	rows, err := q.db.Query(ctx, listCamperCabinExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CamperCabinExplanation
	for rows.Next() {
		var i CamperCabinExplanation
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CamperID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
