// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_session_enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionEnrollment = `-- name: CreateSessionEnrollment :one
INSERT INTO camper_session_enrollments (camp_id, camper_id, session_id, session_age_group_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, camper_id, session_id, session_age_group_id
`

type CreateSessionEnrollmentParams struct {
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	SessionAgeGroupID pgtype.UUID
}

func (q *Queries) CreateSessionEnrollment(ctx context.Context, arg CreateSessionEnrollmentParams) (CamperSessionEnrollment, error) {
	row := q.db.QueryRow(ctx, createSessionEnrollment,
		arg.CampID,
		arg.CamperID,
		arg.SessionID,
		arg.SessionAgeGroupID,
	)
	var i CamperSessionEnrollment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperID,
		&i.SessionID,
		&i.SessionAgeGroupID,
	)
	return i, err
}

const deleteSessionEnrollment = `-- name: DeleteSessionEnrollment :execrows
DELETE FROM camper_session_enrollments
WHERE id = $1 AND camp_id = $2 AND session_id = $3
`

type DeleteSessionEnrollmentParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) DeleteSessionEnrollment(ctx context.Context, arg DeleteSessionEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionEnrollment, arg.ID, arg.CampID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionEnrollment = `-- name: GetSessionEnrollment :one
SELECT
    e.id,
    e.camp_id,
    e.camper_id,
    e.session_age_group_id,
    c.camper_name,
    sag.session_id,
    sag.age_group_id
FROM camper_session_enrollments e
JOIN campers c ON c.id = e.camper_id AND c.camp_id = e.camp_id
JOIN session_age_groups sag ON sag.id = e.session_age_group_id AND sag.camp_id = e.camp_id
WHERE e.id = $1 AND e.camp_id = $2 AND e.session_id = $3
`

type GetSessionEnrollmentParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

type GetSessionEnrollmentRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionAgeGroupID pgtype.UUID
	CamperName        string
	SessionID         pgtype.UUID
	AgeGroupID        pgtype.UUID
}

func (q *Queries) GetSessionEnrollment(ctx context.Context, arg GetSessionEnrollmentParams) (GetSessionEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getSessionEnrollment, arg.ID, arg.CampID, arg.SessionID)
	var i GetSessionEnrollmentRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperID,
		&i.SessionAgeGroupID,
		&i.CamperName,
		&i.SessionID,
		&i.AgeGroupID,
	)
	return i, err
}

const listEnrollmentsBySessionAgeGroup = `-- name: ListEnrollmentsBySessionAgeGroup :many
SELECT
    e.id,
    e.camp_id,
    e.camper_id,
    e.session_age_group_id,
    c.camper_name,
    sag.session_id,
    sag.age_group_id
FROM camper_session_enrollments e
JOIN campers c ON c.id = e.camper_id AND c.camp_id = e.camp_id
JOIN session_age_groups sag ON sag.id = e.session_age_group_id AND sag.camp_id = e.camp_id
WHERE e.session_age_group_id = $1 AND e.camp_id = $2
ORDER BY c.camper_name
`

type ListEnrollmentsBySessionAgeGroupParams struct {
	SessionAgeGroupID pgtype.UUID
	CampID            pgtype.UUID
}

type ListEnrollmentsBySessionAgeGroupRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionAgeGroupID pgtype.UUID
	CamperName        string
	SessionID         pgtype.UUID
	AgeGroupID        pgtype.UUID
}

func (q *Queries) ListEnrollmentsBySessionAgeGroup(ctx context.Context, arg ListEnrollmentsBySessionAgeGroupParams) ([]ListEnrollmentsBySessionAgeGroupRow, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsBySessionAgeGroup, arg.SessionAgeGroupID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsBySessionAgeGroupRow
	for rows.Next() {
		var i ListEnrollmentsBySessionAgeGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CamperID,
			&i.SessionAgeGroupID,
			&i.CamperName,
			&i.SessionID,
			&i.AgeGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEnrollments = `-- name: ListSessionEnrollments :many
SELECT
    e.id,
    e.camp_id,
    e.camper_id,
    e.session_age_group_id,
    c.camper_name,
    sag.session_id,
    sag.age_group_id
FROM camper_session_enrollments e
JOIN campers c ON c.id = e.camper_id AND c.camp_id = e.camp_id
JOIN session_age_groups sag ON sag.id = e.session_age_group_id AND sag.camp_id = e.camp_id
WHERE sag.session_id = $1 AND e.camp_id = $2
ORDER BY c.camper_name
`

type ListSessionEnrollmentsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionEnrollmentsRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionAgeGroupID pgtype.UUID
	CamperName        string
	SessionID         pgtype.UUID
	AgeGroupID        pgtype.UUID
}

func (q *Queries) ListSessionEnrollments(ctx context.Context, arg ListSessionEnrollmentsParams) ([]ListSessionEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listSessionEnrollments, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionEnrollmentsRow
	for rows.Next() {
		var i ListSessionEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CamperID,
			&i.SessionAgeGroupID,
			&i.CamperName,
			&i.SessionID,
			&i.AgeGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
