// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinAssignment = `-- name: CreateCamperCabinAssignment :one
INSERT INTO camper_cabin_assignments (camp_id, solution_id, camper_id, cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, camper_id, cabin_id
`

type CreateCamperCabinAssignmentParams struct {
	CampID     pgtype.UUID
	SolutionID pgtype.UUID
	CamperID   pgtype.UUID
	CabinID    pgtype.UUID
}

func (q *Queries) CreateCamperCabinAssignment(ctx context.Context, arg CreateCamperCabinAssignmentParams) (CamperCabinAssignment, error) {
	row := q.db.QueryRow(ctx, createCamperCabinAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CamperID,
		arg.CabinID,
	)
	var i CamperCabinAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CamperID,
		&i.CabinID,
	)
	return i, err
}

const listCamperCabinAssignmentsBySolution = `-- name: ListCamperCabinAssignmentsBySolution :many
SELECT a.id, a.camp_id, a.solution_id, a.camper_id, a.cabin_id,
       cm.camper_name AS camper_name,
       cb.cabin_name AS cabin_name,
       ag.age_group_name AS age_group_name
FROM camper_cabin_assignments a
JOIN campers cm ON cm.id = a.camper_id
JOIN cabins cb ON cb.id = a.cabin_id
JOIN age_groups ag ON ag.id = cb.default_age_group_id
WHERE a.solution_id = $1 AND a.camp_id = $2
ORDER BY ag.age_group_name, cb.cabin_name, cm.camper_name
`

type ListCamperCabinAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCamperCabinAssignmentsBySolutionRow struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	SolutionID   pgtype.UUID
	CamperID     pgtype.UUID
	CabinID      pgtype.UUID
	CamperName   string
	CabinName    string
	AgeGroupName string
}

func (q *Queries) ListCamperCabinAssignmentsBySolution(ctx context.Context, arg ListCamperCabinAssignmentsBySolutionParams) ([]ListCamperCabinAssignmentsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCamperCabinAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCamperCabinAssignmentsBySolutionRow
	for rows.Next() {
		var i ListCamperCabinAssignmentsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CamperID,
			&i.CabinID,
			&i.CamperName,
			&i.CabinName,
			&i.AgeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
