// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_friend_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperFriendPreference = `-- name: CreateCamperFriendPreference :one
INSERT INTO camper_friend_preferences (camp_id, camper_id, session_id, preferred_camper_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, camper_id, session_id, preferred_camper_id, rank
`

type CreateCamperFriendPreferenceParams struct {
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	PreferredCamperID pgtype.UUID
	Rank              int32
}

func (q *Queries) CreateCamperFriendPreference(ctx context.Context, arg CreateCamperFriendPreferenceParams) (CamperFriendPreference, error) {
	row := q.db.QueryRow(ctx, createCamperFriendPreference,
		arg.CampID,
		arg.CamperID,
		arg.SessionID,
		arg.PreferredCamperID,
		arg.Rank,
	)
	var i CamperFriendPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CamperID,
		&i.SessionID,
		&i.PreferredCamperID,
		&i.Rank,
	)
	return i, err
}

const deleteAllCamperFriendPreferences = `-- name: DeleteAllCamperFriendPreferences :exec
DELETE FROM camper_friend_preferences
WHERE camper_id = $1 AND session_id = $2 AND camp_id = $3
`

type DeleteAllCamperFriendPreferencesParams struct {
	CamperID  pgtype.UUID
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) DeleteAllCamperFriendPreferences(ctx context.Context, arg DeleteAllCamperFriendPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteAllCamperFriendPreferences, arg.CamperID, arg.SessionID, arg.CampID)
	return err
}

const listCamperFriendPreferences = `-- name: ListCamperFriendPreferences :many
SELECT id, camp_id, camper_id, session_id, preferred_camper_id, rank
FROM camper_friend_preferences
WHERE camper_id = $1 AND session_id = $2 AND camp_id = $3
ORDER BY rank
`

type ListCamperFriendPreferencesParams struct {
	CamperID  pgtype.UUID
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListCamperFriendPreferences(ctx context.Context, arg ListCamperFriendPreferencesParams) ([]CamperFriendPreference, error) {
	rows, err := q.db.Query(ctx, listCamperFriendPreferences, arg.CamperID, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CamperFriendPreference
	for rows.Next() {
		var i CamperFriendPreference
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CamperID,
			&i.SessionID,
			&i.PreferredCamperID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCamperFriendPreferences = `-- name: ListSessionCamperFriendPreferences :many
SELECT camper_id, preferred_camper_id, rank
FROM camper_friend_preferences
WHERE session_id = $1 AND camp_id = $2
ORDER BY camper_id, rank
`

type ListSessionCamperFriendPreferencesParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCamperFriendPreferencesRow struct {
	CamperID          pgtype.UUID
	PreferredCamperID pgtype.UUID
	Rank              int32
}

func (q *Queries) ListSessionCamperFriendPreferences(ctx context.Context, arg ListSessionCamperFriendPreferencesParams) ([]ListSessionCamperFriendPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listSessionCamperFriendPreferences, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCamperFriendPreferencesRow
	for rows.Next() {
		var i ListSessionCamperFriendPreferencesRow
		if err := rows.Scan(&i.CamperID, &i.PreferredCamperID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
