// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinAssignment = `-- name: CreateCamperCabinAssignment :one
INSERT INTO camper_cabin_assignments (camp_id, solution_id, camper_id, cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, camper_id, cabin_id
`

type CreateCamperCabinAssignmentParams struct {
	CampID     pgtype.UUID
	SolutionID pgtype.UUID
	CamperID   pgtype.UUID
	CabinID    pgtype.UUID
}

func (q *Queries) CreateCamperCabinAssignment(ctx context.Context, arg CreateCamperCabinAssignmentParams) (CamperCabinAssignment, error) {
	row := q.db.QueryRow(ctx, createCamperCabinAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CamperID,
		arg.CabinID,
	)
	var i CamperCabinAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CamperID,
		&i.CabinID,
	)
	return i, err
}

const listCamperCabinAssignmentsBySolution = `-- name: ListCamperCabinAssignmentsBySolution :many
SELECT id, camp_id, solution_id, camper_id, cabin_id
FROM camper_cabin_assignments
WHERE solution_id = $1 AND camp_id = $2
ORDER BY cabin_id, camper_id
`

type ListCamperCabinAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListCamperCabinAssignmentsBySolution(ctx context.Context, arg ListCamperCabinAssignmentsBySolutionParams) ([]CamperCabinAssignment, error) {
	rows, err := q.db.Query(ctx, listCamperCabinAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CamperCabinAssignment
	for rows.Next() {
		var i CamperCabinAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CamperID,
			&i.CabinID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
