// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: camper_cabin_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamperCabinExplanation = `-- name: CreateCamperCabinExplanation :one
INSERT INTO camper_cabin_explanations (camp_id, solution_id, camper_id, explanation_type, constraint_name, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, solution_id, camper_id, explanation_type, constraint_name, message
`

type CreateCamperCabinExplanationParams struct {
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CamperID        pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

func (q *Queries) CreateCamperCabinExplanation(ctx context.Context, arg CreateCamperCabinExplanationParams) (CamperCabinExplanation, error) {
	row := q.db.QueryRow(ctx, createCamperCabinExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CamperID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Message,
	)
	var i CamperCabinExplanation
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CamperID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Message,
	)
	return i, err
}

const listCamperCabinExplanationsBySolution = `-- name: ListCamperCabinExplanationsBySolution :many
SELECT e.id, e.camp_id, e.solution_id, e.camper_id, e.explanation_type, e.constraint_name, e.message,
       cm.camper_name AS camper_name
FROM camper_cabin_explanations e
JOIN campers cm ON cm.id = e.camper_id
WHERE e.solution_id = $1 AND e.camp_id = $2
ORDER BY cm.camper_name, e.explanation_type, e.message
`

type ListCamperCabinExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCamperCabinExplanationsBySolutionRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CamperID        pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
	CamperName      string
}

func (q *Queries) ListCamperCabinExplanationsBySolution(ctx context.Context, arg ListCamperCabinExplanationsBySolutionParams) ([]ListCamperCabinExplanationsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCamperCabinExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCamperCabinExplanationsBySolutionRow
	for rows.Next() {
		var i ListCamperCabinExplanationsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CamperID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Message,
			&i.CamperName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
