// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCertification = `-- name: CreateCertification :one
INSERT INTO certifications (camp_id, certification_name)
VALUES ($1, $2)
RETURNING id, camp_id, certification_name, archived
`

type CreateCertificationParams struct {
	CampID            pgtype.UUID
	CertificationName string
}

func (q *Queries) CreateCertification(ctx context.Context, arg CreateCertificationParams) (Certification, error) {
	row := q.db.QueryRow(ctx, createCertification, arg.CampID, arg.CertificationName)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CertificationName,
		&i.Archived,
	)
	return i, err
}

const deleteCertification = `-- name: DeleteCertification :execrows
DELETE FROM certifications
WHERE id = $1 AND camp_id = $2
`

type DeleteCertificationParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCertification(ctx context.Context, arg DeleteCertificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertification, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertification = `-- name: GetCertification :one
SELECT id, camp_id, certification_name, archived
FROM certifications
WHERE id = $1 AND camp_id = $2
`

type GetCertificationParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCertification(ctx context.Context, arg GetCertificationParams) (Certification, error) {
	row := q.db.QueryRow(ctx, getCertification, arg.ID, arg.CampID)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CertificationName,
		&i.Archived,
	)
	return i, err
}

const listAllCertifications = `-- name: ListAllCertifications :many
SELECT id, camp_id, certification_name, archived
FROM certifications
WHERE camp_id = $1
ORDER BY certification_name
`

func (q *Queries) ListAllCertifications(ctx context.Context, campID pgtype.UUID) ([]Certification, error) {
	rows, err := q.db.Query(ctx, listAllCertifications, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certification
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CertificationName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedCertifications = `-- name: ListArchivedCertifications :many
SELECT id, camp_id, certification_name, archived
FROM certifications
WHERE camp_id = $1 AND archived = true
ORDER BY certification_name
`

func (q *Queries) ListArchivedCertifications(ctx context.Context, campID pgtype.UUID) ([]Certification, error) {
	rows, err := q.db.Query(ctx, listArchivedCertifications, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certification
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CertificationName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertifications = `-- name: ListCertifications :many
SELECT id, camp_id, certification_name, archived
FROM certifications
WHERE camp_id = $1 AND archived = false
ORDER BY certification_name
`

func (q *Queries) ListCertifications(ctx context.Context, campID pgtype.UUID) ([]Certification, error) {
	rows, err := q.db.Query(ctx, listCertifications, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certification
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CertificationName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertification = `-- name: UpdateCertification :one
UPDATE certifications
SET certification_name = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, certification_name, archived
`

type UpdateCertificationParams struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CertificationName string
}

func (q *Queries) UpdateCertification(ctx context.Context, arg UpdateCertificationParams) (Certification, error) {
	row := q.db.QueryRow(ctx, updateCertification, arg.ID, arg.CampID, arg.CertificationName)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CertificationName,
		&i.Archived,
	)
	return i, err
}
