// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_age_group_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorAgeGroupPreference = `-- name: CreateCounselorAgeGroupPreference :one
INSERT INTO counselor_age_group_preferences (camp_id, counselor_id, session_id, age_group_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, counselor_id, session_id, age_group_id, rank
`

type CreateCounselorAgeGroupPreferenceParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	Rank        int32
}

func (q *Queries) CreateCounselorAgeGroupPreference(ctx context.Context, arg CreateCounselorAgeGroupPreferenceParams) (CounselorAgeGroupPreference, error) {
	row := q.db.QueryRow(ctx, createCounselorAgeGroupPreference,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.AgeGroupID,
		arg.Rank,
	)
	var i CounselorAgeGroupPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.Rank,
	)
	return i, err
}

const deleteAllCounselorAgeGroupPreferences = `-- name: DeleteAllCounselorAgeGroupPreferences :exec
DELETE FROM counselor_age_group_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
`

type DeleteAllCounselorAgeGroupPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) DeleteAllCounselorAgeGroupPreferences(ctx context.Context, arg DeleteAllCounselorAgeGroupPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteAllCounselorAgeGroupPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	return err
}

const listCounselorAgeGroupPreferences = `-- name: ListCounselorAgeGroupPreferences :many
SELECT id, camp_id, counselor_id, session_id, age_group_id, rank
FROM counselor_age_group_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
ORDER BY rank
`

type ListCounselorAgeGroupPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) ListCounselorAgeGroupPreferences(ctx context.Context, arg ListCounselorAgeGroupPreferencesParams) ([]CounselorAgeGroupPreference, error) {
	rows, err := q.db.Query(ctx, listCounselorAgeGroupPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorAgeGroupPreference
	for rows.Next() {
		var i CounselorAgeGroupPreference
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.SessionID,
			&i.AgeGroupID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAgeGroupPreferences = `-- name: ListSessionAgeGroupPreferences :many
SELECT counselor_id, age_group_id, rank
FROM counselor_age_group_preferences
WHERE session_id = $1 AND camp_id = $2
ORDER BY counselor_id, rank
`

type ListSessionAgeGroupPreferencesParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionAgeGroupPreferencesRow struct {
	CounselorID pgtype.UUID
	AgeGroupID  pgtype.UUID
	Rank        int32
}

func (q *Queries) ListSessionAgeGroupPreferences(ctx context.Context, arg ListSessionAgeGroupPreferencesParams) ([]ListSessionAgeGroupPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listSessionAgeGroupPreferences, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionAgeGroupPreferencesRow
	for rows.Next() {
		var i ListSessionAgeGroupPreferencesRow
		if err := rows.Scan(&i.CounselorID, &i.AgeGroupID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
