// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinAssignment = `-- name: CreateCounselorCabinAssignment :one
INSERT INTO counselor_cabin_assignments (camp_id, solution_id, counselor_id, cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, counselor_id, cabin_id
`

type CreateCounselorCabinAssignmentParams struct {
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
	CabinID     pgtype.UUID
}

func (q *Queries) CreateCounselorCabinAssignment(ctx context.Context, arg CreateCounselorCabinAssignmentParams) (CounselorCabinAssignment, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.CabinID,
	)
	var i CounselorCabinAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.CabinID,
	)
	return i, err
}

const listCounselorCabinAssignmentsBySolution = `-- name: ListCounselorCabinAssignmentsBySolution :many
SELECT id, camp_id, solution_id, counselor_id, cabin_id
FROM counselor_cabin_assignments
WHERE solution_id = $1 AND camp_id = $2
ORDER BY cabin_id, counselor_id
`

type ListCounselorCabinAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListCounselorCabinAssignmentsBySolution(ctx context.Context, arg ListCounselorCabinAssignmentsBySolutionParams) ([]CounselorCabinAssignment, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorCabinAssignment
	for rows.Next() {
		var i CounselorCabinAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.CabinID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
