// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinExplanation = `-- name: CreateCounselorCabinExplanation :one
INSERT INTO counselor_cabin_explanations (camp_id, solution_id, counselor_id, explanation_type, constraint_name, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, solution_id, counselor_id, explanation_type, constraint_name, message
`

type CreateCounselorCabinExplanationParams struct {
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

func (q *Queries) CreateCounselorCabinExplanation(ctx context.Context, arg CreateCounselorCabinExplanationParams) (CounselorCabinExplanation, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Message,
	)
	var i CounselorCabinExplanation
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Message,
	)
	return i, err
}

const listCounselorCabinExplanationsBySolution = `-- name: ListCounselorCabinExplanationsBySolution :many
SELECT e.id, e.camp_id, e.solution_id, e.counselor_id, e.explanation_type, e.constraint_name, e.message,
       co.counselor_name AS counselor_name
FROM counselor_cabin_explanations e
JOIN counselors co ON co.id = e.counselor_id
WHERE e.solution_id = $1 AND e.camp_id = $2
ORDER BY co.counselor_name, e.explanation_type, e.message
`

type ListCounselorCabinExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorCabinExplanationsBySolutionRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
	CounselorName   string
}

func (q *Queries) ListCounselorCabinExplanationsBySolution(ctx context.Context, arg ListCounselorCabinExplanationsBySolutionParams) ([]ListCounselorCabinExplanationsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCabinExplanationsBySolutionRow
	for rows.Next() {
		var i ListCounselorCabinExplanationsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Message,
			&i.CounselorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
