// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_certifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCertification = `-- name: CreateCounselorCertification :one
INSERT INTO counselor_certifications (camp_id, counselor_id, certification_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, counselor_id, certification_id
`

type CreateCounselorCertificationParams struct {
	CampID          pgtype.UUID
	CounselorID     pgtype.UUID
	CertificationID pgtype.UUID
}

func (q *Queries) CreateCounselorCertification(ctx context.Context, arg CreateCounselorCertificationParams) (CounselorCertification, error) {
	row := q.db.QueryRow(ctx, createCounselorCertification, arg.CampID, arg.CounselorID, arg.CertificationID)
	var i CounselorCertification
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.CertificationID,
	)
	return i, err
}

const deleteCounselorCertification = `-- name: DeleteCounselorCertification :execrows
DELETE FROM counselor_certifications
WHERE id = $1 AND camp_id = $2 AND counselor_id = $3
`

type DeleteCounselorCertificationParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) DeleteCounselorCertification(ctx context.Context, arg DeleteCounselorCertificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorCertification, arg.ID, arg.CampID, arg.CounselorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCounselorCertifications = `-- name: ListCounselorCertifications :many
SELECT cc.id, cc.camp_id, cc.counselor_id, cc.certification_id, c.certification_name
FROM counselor_certifications cc
JOIN certifications c ON c.id = cc.certification_id
WHERE cc.counselor_id = $1 AND cc.camp_id = $2
ORDER BY c.certification_name
`

type ListCounselorCertificationsParams struct {
	CounselorID pgtype.UUID
	CampID      pgtype.UUID
}

type ListCounselorCertificationsRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CounselorID       pgtype.UUID
	CertificationID   pgtype.UUID
	CertificationName string
}

func (q *Queries) ListCounselorCertifications(ctx context.Context, arg ListCounselorCertificationsParams) ([]ListCounselorCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCertifications, arg.CounselorID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCertificationsRow
	for rows.Next() {
		var i ListCounselorCertificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.CertificationID,
			&i.CertificationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCounselorCertifications = `-- name: ListSessionCounselorCertifications :many
SELECT cc.counselor_id, cc.certification_id
FROM counselor_certifications cc
JOIN counselors co ON co.id = cc.counselor_id AND co.camp_id = cc.camp_id
WHERE cc.camp_id = $1 AND co.counselor_enabled = true
ORDER BY cc.counselor_id, cc.certification_id
`

type ListSessionCounselorCertificationsRow struct {
	CounselorID     pgtype.UUID
	CertificationID pgtype.UUID
}

func (q *Queries) ListSessionCounselorCertifications(ctx context.Context, campID pgtype.UUID) ([]ListSessionCounselorCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listSessionCounselorCertifications, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCounselorCertificationsRow
	for rows.Next() {
		var i ListSessionCounselorCertificationsRow
		if err := rows.Scan(&i.CounselorID, &i.CertificationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
