// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivityPreference = `-- name: CreateCounselorActivityPreference :one
INSERT INTO counselor_activity_preferences (camp_id, counselor_id, session_id, activity_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, counselor_id, session_id, activity_id, rank
`

type CreateCounselorActivityPreferenceParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	ActivityID  pgtype.UUID
	Rank        int32
}

func (q *Queries) CreateCounselorActivityPreference(ctx context.Context, arg CreateCounselorActivityPreferenceParams) (CounselorActivityPreference, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityPreference,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.ActivityID,
		arg.Rank,
	)
	var i CounselorActivityPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.ActivityID,
		&i.Rank,
	)
	return i, err
}

const deleteCounselorActivityPreference = `-- name: DeleteCounselorActivityPreference :execrows
DELETE FROM counselor_activity_preferences
WHERE id = $1 AND camp_id = $2 AND session_id = $3 AND counselor_id = $4
`

type DeleteCounselorActivityPreferenceParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SessionID   pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) DeleteCounselorActivityPreference(ctx context.Context, arg DeleteCounselorActivityPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorActivityPreference,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.CounselorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselorActivityPreference = `-- name: GetCounselorActivityPreference :one
SELECT id, camp_id, counselor_id, session_id, activity_id, rank
FROM counselor_activity_preferences
WHERE id = $1 AND camp_id = $2 AND session_id = $3 AND counselor_id = $4
`

type GetCounselorActivityPreferenceParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SessionID   pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) GetCounselorActivityPreference(ctx context.Context, arg GetCounselorActivityPreferenceParams) (CounselorActivityPreference, error) {
	row := q.db.QueryRow(ctx, getCounselorActivityPreference,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.CounselorID,
	)
	var i CounselorActivityPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.ActivityID,
		&i.Rank,
	)
	return i, err
}

const listCounselorActivityPreferences = `-- name: ListCounselorActivityPreferences :many
SELECT id, camp_id, counselor_id, session_id, activity_id, rank
FROM counselor_activity_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
ORDER BY rank
`

type ListCounselorActivityPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) ListCounselorActivityPreferences(ctx context.Context, arg ListCounselorActivityPreferencesParams) ([]CounselorActivityPreference, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorActivityPreference
	for rows.Next() {
		var i CounselorActivityPreference
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.SessionID,
			&i.ActivityID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionActivityPreferences = `-- name: ListSessionActivityPreferences :many
SELECT counselor_id, activity_id, rank
FROM counselor_activity_preferences
WHERE session_id = $1 AND camp_id = $2
ORDER BY counselor_id, rank
`

type ListSessionActivityPreferencesParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionActivityPreferencesRow struct {
	CounselorID pgtype.UUID
	ActivityID  pgtype.UUID
	Rank        int32
}

func (q *Queries) ListSessionActivityPreferences(ctx context.Context, arg ListSessionActivityPreferencesParams) ([]ListSessionActivityPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listSessionActivityPreferences, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionActivityPreferencesRow
	for rows.Next() {
		var i ListSessionActivityPreferencesRow
		if err := rows.Scan(&i.CounselorID, &i.ActivityID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounselorActivityPreference = `-- name: UpdateCounselorActivityPreference :one
UPDATE counselor_activity_preferences
SET activity_id = $5,
    rank = $6
WHERE id = $1 AND camp_id = $2 AND session_id = $3 AND counselor_id = $4
RETURNING id, camp_id, counselor_id, session_id, activity_id, rank
`

type UpdateCounselorActivityPreferenceParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SessionID   pgtype.UUID
	CounselorID pgtype.UUID
	ActivityID  pgtype.UUID
	Rank        int32
}

func (q *Queries) UpdateCounselorActivityPreference(ctx context.Context, arg UpdateCounselorActivityPreferenceParams) (CounselorActivityPreference, error) {
	row := q.db.QueryRow(ctx, updateCounselorActivityPreference,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.CounselorID,
		arg.ActivityID,
		arg.Rank,
	)
	var i CounselorActivityPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.ActivityID,
		&i.Rank,
	)
	return i, err
}
