// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_overrides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinOverride = `-- name: CreateCounselorCabinOverride :one
INSERT INTO counselor_cabin_overrides (camp_id, session_id, counselor_id, session_age_group_cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, counselor_id, session_age_group_cabin_id, created_at
`

type CreateCounselorCabinOverrideParams struct {
	CampID                 pgtype.UUID
	SessionID              pgtype.UUID
	CounselorID            pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
}

func (q *Queries) CreateCounselorCabinOverride(ctx context.Context, arg CreateCounselorCabinOverrideParams) (CounselorCabinOverride, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinOverride,
		arg.CampID,
		arg.SessionID,
		arg.CounselorID,
		arg.SessionAgeGroupCabinID,
	)
	var i CounselorCabinOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
		&i.SessionAgeGroupCabinID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCounselorCabinOverride = `-- name: DeleteCounselorCabinOverride :execrows
DELETE FROM counselor_cabin_overrides
WHERE id = $1 AND camp_id = $2
`

type DeleteCounselorCabinOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCounselorCabinOverride(ctx context.Context, arg DeleteCounselorCabinOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorCabinOverride, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselorCabinOverride = `-- name: GetCounselorCabinOverride :one
SELECT id, camp_id, session_id, counselor_id, session_age_group_cabin_id, created_at
FROM counselor_cabin_overrides
WHERE id = $1 AND camp_id = $2
`

type GetCounselorCabinOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCounselorCabinOverride(ctx context.Context, arg GetCounselorCabinOverrideParams) (CounselorCabinOverride, error) {
	row := q.db.QueryRow(ctx, getCounselorCabinOverride, arg.ID, arg.CampID)
	var i CounselorCabinOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
		&i.SessionAgeGroupCabinID,
		&i.CreatedAt,
	)
	return i, err
}

const listCounselorCabinOverridesBySession = `-- name: ListCounselorCabinOverridesBySession :many
SELECT o.id, o.camp_id, o.session_id, o.counselor_id, o.session_age_group_cabin_id, o.created_at,
       sagc.cabin_id AS cabin_id,
       co.first_name AS counselor_first_name,
       co.last_name AS counselor_last_name,
       btrim(co.first_name || ' ' || co.last_name)::text AS counselor_name,
       cb.cabin_name AS cabin_name,
       ag.age_group_name AS age_group_name
FROM counselor_cabin_overrides o
JOIN counselors co ON co.id = o.counselor_id
JOIN session_age_group_cabins sagc ON sagc.id = o.session_age_group_cabin_id
JOIN cabins cb ON cb.id = sagc.cabin_id
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
JOIN age_groups ag ON ag.id = sag.age_group_id
WHERE o.session_id = $1 AND o.camp_id = $2
ORDER BY ag.age_group_name, cb.cabin_name, co.last_name, co.first_name
`

type ListCounselorCabinOverridesBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCounselorCabinOverridesBySessionRow struct {
	ID                     pgtype.UUID
	CampID                 pgtype.UUID
	SessionID              pgtype.UUID
	CounselorID            pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	CabinID                pgtype.UUID
	CounselorFirstName     string
	CounselorLastName      string
	CounselorName          string
	CabinName              string
	AgeGroupName           string
}

func (q *Queries) ListCounselorCabinOverridesBySession(ctx context.Context, arg ListCounselorCabinOverridesBySessionParams) ([]ListCounselorCabinOverridesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinOverridesBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCabinOverridesBySessionRow
	for rows.Next() {
		var i ListCounselorCabinOverridesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.CounselorID,
			&i.SessionAgeGroupCabinID,
			&i.CreatedAt,
			&i.CabinID,
			&i.CounselorFirstName,
			&i.CounselorLastName,
			&i.CounselorName,
			&i.CabinName,
			&i.AgeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounselorCabinOverridesForSolver = `-- name: ListCounselorCabinOverridesForSolver :many
SELECT o.counselor_id, o.session_age_group_cabin_id
FROM counselor_cabin_overrides o
WHERE o.session_id = $1 AND o.camp_id = $2
`

type ListCounselorCabinOverridesForSolverParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCounselorCabinOverridesForSolverRow struct {
	CounselorID            pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
}

func (q *Queries) ListCounselorCabinOverridesForSolver(ctx context.Context, arg ListCounselorCabinOverridesForSolverParams) ([]ListCounselorCabinOverridesForSolverRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinOverridesForSolver, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCabinOverridesForSolverRow
	for rows.Next() {
		var i ListCounselorCabinOverridesForSolverRow
		if err := rows.Scan(&i.CounselorID, &i.SessionAgeGroupCabinID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
