// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinExplanation = `-- name: CreateCounselorCabinExplanation :one
INSERT INTO counselor_cabin_explanations (camp_id, solution_id, counselor_id, explanation_type, constraint_name, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, solution_id, counselor_id, explanation_type, constraint_name, message
`

type CreateCounselorCabinExplanationParams struct {
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

func (q *Queries) CreateCounselorCabinExplanation(ctx context.Context, arg CreateCounselorCabinExplanationParams) (CounselorCabinExplanation, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Message,
	)
	var i CounselorCabinExplanation
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Message,
	)
	return i, err
}

const listCounselorCabinExplanationsBySolution = `-- name: ListCounselorCabinExplanationsBySolution :many
SELECT id, camp_id, solution_id, counselor_id, explanation_type, constraint_name, message
FROM counselor_cabin_explanations
WHERE solution_id = $1 AND camp_id = $2
ORDER BY counselor_id, explanation_type
`

type ListCounselorCabinExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

func (q *Queries) ListCounselorCabinExplanationsBySolution(ctx context.Context, arg ListCounselorCabinExplanationsBySolutionParams) ([]CounselorCabinExplanation, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorCabinExplanation
	for rows.Next() {
		var i CounselorCabinExplanation
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
