// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivityAssignment = `-- name: CreateCounselorActivityAssignment :one
INSERT INTO counselor_activity_assignments (camp_id, solution_id, counselor_id, session_activity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, counselor_id, session_activity_id
`

type CreateCounselorActivityAssignmentParams struct {
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
}

func (q *Queries) CreateCounselorActivityAssignment(ctx context.Context, arg CreateCounselorActivityAssignmentParams) (CounselorActivityAssignment, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.SessionActivityID,
	)
	var i CounselorActivityAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.SessionActivityID,
	)
	return i, err
}

const listCounselorActivityAssignmentsBySolution = `-- name: ListCounselorActivityAssignmentsBySolution :many
SELECT a.id, a.camp_id, a.solution_id, a.counselor_id, a.session_activity_id,
       co.first_name AS counselor_first_name,
       co.last_name AS counselor_last_name,
       btrim(co.first_name || ' ' || co.last_name)::text AS counselor_name,
       act.activity_name AS activity_name,
       ts.time_slot_name AS time_slot_name,
       sts.sort_order AS sort_order
FROM counselor_activity_assignments a
JOIN counselors co ON co.id = a.counselor_id
JOIN session_activities sa ON sa.id = a.session_activity_id
JOIN activities act ON act.id = sa.activity_id
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
JOIN time_slots ts ON ts.id = sts.time_slot_id
WHERE a.solution_id = $1 AND a.camp_id = $2
ORDER BY sts.sort_order, sts.id, act.activity_name, co.last_name, co.first_name
`

type ListCounselorActivityAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorActivityAssignmentsBySolutionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SolutionID         pgtype.UUID
	CounselorID        pgtype.UUID
	SessionActivityID  pgtype.UUID
	CounselorFirstName string
	CounselorLastName  string
	CounselorName      string
	ActivityName       string
	TimeSlotName       string
	SortOrder          int32
}

func (q *Queries) ListCounselorActivityAssignmentsBySolution(ctx context.Context, arg ListCounselorActivityAssignmentsBySolutionParams) ([]ListCounselorActivityAssignmentsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityAssignmentsBySolutionRow
	for rows.Next() {
		var i ListCounselorActivityAssignmentsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.SessionActivityID,
			&i.CounselorFirstName,
			&i.CounselorLastName,
			&i.CounselorName,
			&i.ActivityName,
			&i.TimeSlotName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
