// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_unassigned.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinUnassigned = `-- name: CreateCounselorCabinUnassigned :one
INSERT INTO counselor_cabin_unassigned (camp_id, solution_id, counselor_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, solution_id, counselor_id
`

type CreateCounselorCabinUnassignedParams struct {
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) CreateCounselorCabinUnassigned(ctx context.Context, arg CreateCounselorCabinUnassignedParams) (CounselorCabinUnassigned, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinUnassigned, arg.CampID, arg.SolutionID, arg.CounselorID)
	var i CounselorCabinUnassigned
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
	)
	return i, err
}

const listCounselorCabinUnassignedBySolution = `-- name: ListCounselorCabinUnassignedBySolution :many
SELECT u.id, u.camp_id, u.solution_id, u.counselor_id,
       (co.first_name || ' ' || co.last_name)::text AS counselor_name
FROM counselor_cabin_unassigned u
JOIN counselors co ON co.id = u.counselor_id
WHERE u.solution_id = $1 AND u.camp_id = $2
ORDER BY co.last_name, co.first_name
`

type ListCounselorCabinUnassignedBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorCabinUnassignedBySolutionRow struct {
	ID            pgtype.UUID
	CampID        pgtype.UUID
	SolutionID    pgtype.UUID
	CounselorID   pgtype.UUID
	CounselorName string
}

func (q *Queries) ListCounselorCabinUnassignedBySolution(ctx context.Context, arg ListCounselorCabinUnassignedBySolutionParams) ([]ListCounselorCabinUnassignedBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinUnassignedBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCabinUnassignedBySolutionRow
	for rows.Next() {
		var i ListCounselorCabinUnassignedBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.CounselorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
