// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinAssignment = `-- name: CreateCounselorCabinAssignment :one
INSERT INTO counselor_cabin_assignments (camp_id, solution_id, counselor_id, cabin_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, solution_id, counselor_id, cabin_id
`

type CreateCounselorCabinAssignmentParams struct {
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
	CabinID     pgtype.UUID
}

func (q *Queries) CreateCounselorCabinAssignment(ctx context.Context, arg CreateCounselorCabinAssignmentParams) (CounselorCabinAssignment, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinAssignment,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.CabinID,
	)
	var i CounselorCabinAssignment
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.CabinID,
	)
	return i, err
}

const listCounselorCabinAssignmentsBySolution = `-- name: ListCounselorCabinAssignmentsBySolution :many
SELECT a.id, a.camp_id, a.solution_id, a.counselor_id, a.cabin_id,
       co.counselor_name AS counselor_name,
       cb.cabin_name AS cabin_name,
       ag.age_group_name AS age_group_name
FROM counselor_cabin_assignments a
JOIN counselors co ON co.id = a.counselor_id
JOIN cabins cb ON cb.id = a.cabin_id
JOIN age_groups ag ON ag.id = cb.default_age_group_id
WHERE a.solution_id = $1 AND a.camp_id = $2
ORDER BY ag.age_group_name, cb.cabin_name, co.counselor_name
`

type ListCounselorCabinAssignmentsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorCabinAssignmentsBySolutionRow struct {
	ID            pgtype.UUID
	CampID        pgtype.UUID
	SolutionID    pgtype.UUID
	CounselorID   pgtype.UUID
	CabinID       pgtype.UUID
	CounselorName string
	CabinName     string
	AgeGroupName  string
}

func (q *Queries) ListCounselorCabinAssignmentsBySolution(ctx context.Context, arg ListCounselorCabinAssignmentsBySolutionParams) ([]ListCounselorCabinAssignmentsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinAssignmentsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorCabinAssignmentsBySolutionRow
	for rows.Next() {
		var i ListCounselorCabinAssignmentsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.CabinID,
			&i.CounselorName,
			&i.CabinName,
			&i.AgeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
