// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselor = `-- name: CreateCounselor :one
INSERT INTO counselors (camp_id, counselor_name, junior_counselor)
VALUES ($1, $2, $3)
RETURNING id, camp_id, counselor_name, junior_counselor, counselor_enabled
`

type CreateCounselorParams struct {
	CampID          pgtype.UUID
	CounselorName   string
	JuniorCounselor bool
}

func (q *Queries) CreateCounselor(ctx context.Context, arg CreateCounselorParams) (Counselor, error) {
	row := q.db.QueryRow(ctx, createCounselor, arg.CampID, arg.CounselorName, arg.JuniorCounselor)
	var i Counselor
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorName,
		&i.JuniorCounselor,
		&i.CounselorEnabled,
	)
	return i, err
}

const deleteCounselor = `-- name: DeleteCounselor :execrows
DELETE FROM counselors
WHERE id = $1
`

func (q *Queries) DeleteCounselor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselor = `-- name: GetCounselor :one
SELECT id, camp_id, counselor_name, junior_counselor, counselor_enabled
FROM counselors
WHERE id = $1
`

func (q *Queries) GetCounselor(ctx context.Context, id pgtype.UUID) (Counselor, error) {
	row := q.db.QueryRow(ctx, getCounselor, id)
	var i Counselor
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorName,
		&i.JuniorCounselor,
		&i.CounselorEnabled,
	)
	return i, err
}

const listCounselors = `-- name: ListCounselors :many
SELECT id, camp_id, counselor_name, junior_counselor, counselor_enabled
FROM counselors
WHERE camp_id = $1
ORDER BY counselor_name
`

func (q *Queries) ListCounselors(ctx context.Context, campID pgtype.UUID) ([]Counselor, error) {
	rows, err := q.db.Query(ctx, listCounselors, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counselor
	for rows.Next() {
		var i Counselor
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorName,
			&i.JuniorCounselor,
			&i.CounselorEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounselor = `-- name: UpdateCounselor :one
UPDATE counselors
SET counselor_name = $2,
    junior_counselor = $3,
    counselor_enabled = $4
WHERE id = $1
RETURNING id, camp_id, counselor_name, junior_counselor, counselor_enabled
`

type UpdateCounselorParams struct {
	ID               pgtype.UUID
	CounselorName    string
	JuniorCounselor  bool
	CounselorEnabled bool
}

func (q *Queries) UpdateCounselor(ctx context.Context, arg UpdateCounselorParams) (Counselor, error) {
	row := q.db.QueryRow(ctx, updateCounselor,
		arg.ID,
		arg.CounselorName,
		arg.JuniorCounselor,
		arg.CounselorEnabled,
	)
	var i Counselor
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorName,
		&i.JuniorCounselor,
		&i.CounselorEnabled,
	)
	return i, err
}
