// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cocounselor_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCocounselorPreference = `-- name: CreateCounselorCocounselorPreference :one
INSERT INTO counselor_cocounselor_preferences (camp_id, counselor_id, session_id, preferred_counselor_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, counselor_id, session_id, preferred_counselor_id, rank
`

type CreateCounselorCocounselorPreferenceParams struct {
	CampID               pgtype.UUID
	CounselorID          pgtype.UUID
	SessionID            pgtype.UUID
	PreferredCounselorID pgtype.UUID
	Rank                 int32
}

func (q *Queries) CreateCounselorCocounselorPreference(ctx context.Context, arg CreateCounselorCocounselorPreferenceParams) (CounselorCocounselorPreference, error) {
	row := q.db.QueryRow(ctx, createCounselorCocounselorPreference,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.PreferredCounselorID,
		arg.Rank,
	)
	var i CounselorCocounselorPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.PreferredCounselorID,
		&i.Rank,
	)
	return i, err
}

const deleteAllCounselorCocounselorPreferences = `-- name: DeleteAllCounselorCocounselorPreferences :exec
DELETE FROM counselor_cocounselor_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
`

type DeleteAllCounselorCocounselorPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) DeleteAllCounselorCocounselorPreferences(ctx context.Context, arg DeleteAllCounselorCocounselorPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteAllCounselorCocounselorPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	return err
}

const listCounselorCocounselorPreferences = `-- name: ListCounselorCocounselorPreferences :many
SELECT id, camp_id, counselor_id, session_id, preferred_counselor_id, rank
FROM counselor_cocounselor_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
ORDER BY rank
`

type ListCounselorCocounselorPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) ListCounselorCocounselorPreferences(ctx context.Context, arg ListCounselorCocounselorPreferencesParams) ([]CounselorCocounselorPreference, error) {
	rows, err := q.db.Query(ctx, listCounselorCocounselorPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorCocounselorPreference
	for rows.Next() {
		var i CounselorCocounselorPreference
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.SessionID,
			&i.PreferredCounselorID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCocounselorPreferences = `-- name: ListSessionCocounselorPreferences :many
SELECT counselor_id, preferred_counselor_id, rank
FROM counselor_cocounselor_preferences
WHERE session_id = $1 AND camp_id = $2
ORDER BY counselor_id, rank
`

type ListSessionCocounselorPreferencesParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCocounselorPreferencesRow struct {
	CounselorID          pgtype.UUID
	PreferredCounselorID pgtype.UUID
	Rank                 int32
}

func (q *Queries) ListSessionCocounselorPreferences(ctx context.Context, arg ListSessionCocounselorPreferencesParams) ([]ListSessionCocounselorPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listSessionCocounselorPreferences, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCocounselorPreferencesRow
	for rows.Next() {
		var i ListSessionCocounselorPreferencesRow
		if err := rows.Scan(&i.CounselorID, &i.PreferredCounselorID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
