// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_session_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorSessionHistoryEntry = `-- name: CreateCounselorSessionHistoryEntry :one
INSERT INTO counselor_session_history (camp_id, counselor_id, session_id, age_group_id, cabin_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, counselor_id, session_id, age_group_id, cabin_id
`

type CreateCounselorSessionHistoryEntryParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	CabinID     pgtype.UUID
}

func (q *Queries) CreateCounselorSessionHistoryEntry(ctx context.Context, arg CreateCounselorSessionHistoryEntryParams) (CounselorSessionHistory, error) {
	row := q.db.QueryRow(ctx, createCounselorSessionHistoryEntry,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.AgeGroupID,
		arg.CabinID,
	)
	var i CounselorSessionHistory
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.CabinID,
	)
	return i, err
}

const deleteCounselorSessionHistoryEntry = `-- name: DeleteCounselorSessionHistoryEntry :execrows
DELETE FROM counselor_session_history
WHERE id = $1 AND camp_id = $2 AND counselor_id = $3
`

type DeleteCounselorSessionHistoryEntryParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) DeleteCounselorSessionHistoryEntry(ctx context.Context, arg DeleteCounselorSessionHistoryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorSessionHistoryEntry, arg.ID, arg.CampID, arg.CounselorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselorHistorySummary = `-- name: GetCounselorHistorySummary :many
SELECT
    csh.id,
    s.session_name,
    se.id AS season_id,
    se.season_name,
    ag.age_group_name,
    c.cabin_name
FROM counselor_session_history csh
JOIN sessions s ON s.id = csh.session_id
JOIN seasons se ON se.id = s.season_id
JOIN age_groups ag ON ag.id = csh.age_group_id
LEFT JOIN cabins c ON c.id = csh.cabin_id
WHERE csh.counselor_id = $1
  AND csh.camp_id = $2
  AND ($3::uuid IS NULL OR se.id = $3::uuid)
ORDER BY se.season_name, s.session_name
`

type GetCounselorHistorySummaryParams struct {
	CounselorID pgtype.UUID
	CampID      pgtype.UUID
	SeasonID    pgtype.UUID
}

type GetCounselorHistorySummaryRow struct {
	ID           pgtype.UUID
	SessionName  string
	SeasonID     pgtype.UUID
	SeasonName   string
	AgeGroupName string
	CabinName    pgtype.Text
}

func (q *Queries) GetCounselorHistorySummary(ctx context.Context, arg GetCounselorHistorySummaryParams) ([]GetCounselorHistorySummaryRow, error) {
	rows, err := q.db.Query(ctx, getCounselorHistorySummary, arg.CounselorID, arg.CampID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCounselorHistorySummaryRow
	for rows.Next() {
		var i GetCounselorHistorySummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionName,
			&i.SeasonID,
			&i.SeasonName,
			&i.AgeGroupName,
			&i.CabinName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCounselorSessionHistoryEntry = `-- name: GetCounselorSessionHistoryEntry :one
SELECT id, camp_id, counselor_id, session_id, age_group_id, cabin_id
FROM counselor_session_history
WHERE id = $1 AND camp_id = $2 AND counselor_id = $3
`

type GetCounselorSessionHistoryEntryParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) GetCounselorSessionHistoryEntry(ctx context.Context, arg GetCounselorSessionHistoryEntryParams) (CounselorSessionHistory, error) {
	row := q.db.QueryRow(ctx, getCounselorSessionHistoryEntry, arg.ID, arg.CampID, arg.CounselorID)
	var i CounselorSessionHistory
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.CabinID,
	)
	return i, err
}

const listCounselorSessionHistory = `-- name: ListCounselorSessionHistory :many
SELECT id, camp_id, counselor_id, session_id, age_group_id, cabin_id
FROM counselor_session_history
WHERE counselor_id = $1 AND camp_id = $2
ORDER BY session_id
`

type ListCounselorSessionHistoryParams struct {
	CounselorID pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) ListCounselorSessionHistory(ctx context.Context, arg ListCounselorSessionHistoryParams) ([]CounselorSessionHistory, error) {
	rows, err := q.db.Query(ctx, listCounselorSessionHistory, arg.CounselorID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorSessionHistory
	for rows.Next() {
		var i CounselorSessionHistory
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.SessionID,
			&i.AgeGroupID,
			&i.CabinID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionHistory = `-- name: ListSessionHistory :many
SELECT counselor_id, age_group_id, cabin_id
FROM counselor_session_history
WHERE session_id = $1 AND camp_id = $2
`

type ListSessionHistoryParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionHistoryRow struct {
	CounselorID pgtype.UUID
	AgeGroupID  pgtype.UUID
	CabinID     pgtype.UUID
}

func (q *Queries) ListSessionHistory(ctx context.Context, arg ListSessionHistoryParams) ([]ListSessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSessionHistory, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionHistoryRow
	for rows.Next() {
		var i ListSessionHistoryRow
		if err := rows.Scan(&i.CounselorID, &i.AgeGroupID, &i.CabinID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounselorSessionHistoryEntry = `-- name: UpdateCounselorSessionHistoryEntry :one
UPDATE counselor_session_history
SET session_id = $4,
    age_group_id = $5,
    cabin_id = $6
WHERE id = $1 AND camp_id = $2 AND counselor_id = $3
RETURNING id, camp_id, counselor_id, session_id, age_group_id, cabin_id
`

type UpdateCounselorSessionHistoryEntryParams struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	CabinID     pgtype.UUID
}

func (q *Queries) UpdateCounselorSessionHistoryEntry(ctx context.Context, arg UpdateCounselorSessionHistoryEntryParams) (CounselorSessionHistory, error) {
	row := q.db.QueryRow(ctx, updateCounselorSessionHistoryEntry,
		arg.ID,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.AgeGroupID,
		arg.CabinID,
	)
	var i CounselorSessionHistory
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.CabinID,
	)
	return i, err
}
