// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_explanations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivityExplanation = `-- name: CreateCounselorActivityExplanation :one
INSERT INTO counselor_activity_explanations (camp_id, solution_id, counselor_id, session_activity_id, explanation_type, constraint_name, rank, message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, camp_id, solution_id, counselor_id, session_activity_id, explanation_type, constraint_name, rank, message
`

type CreateCounselorActivityExplanationParams struct {
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
	ExplanationType   string
	ConstraintName    pgtype.Text
	Rank              pgtype.Int4
	Message           string
}

type CreateCounselorActivityExplanationRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
	ExplanationType   string
	ConstraintName    pgtype.Text
	Rank              pgtype.Int4
	Message           string
}

func (q *Queries) CreateCounselorActivityExplanation(ctx context.Context, arg CreateCounselorActivityExplanationParams) (CreateCounselorActivityExplanationRow, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityExplanation,
		arg.CampID,
		arg.SolutionID,
		arg.CounselorID,
		arg.SessionActivityID,
		arg.ExplanationType,
		arg.ConstraintName,
		arg.Rank,
		arg.Message,
	)
	var i CreateCounselorActivityExplanationRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
		&i.SessionActivityID,
		&i.ExplanationType,
		&i.ConstraintName,
		&i.Rank,
		&i.Message,
	)
	return i, err
}

const listCounselorActivityExplanationsBySolution = `-- name: ListCounselorActivityExplanationsBySolution :many
SELECT e.id, e.camp_id, e.solution_id, e.counselor_id, e.session_activity_id, e.explanation_type, e.constraint_name, e.rank, e.message,
       co.first_name AS counselor_first_name,
       co.last_name AS counselor_last_name,
       btrim(co.first_name || ' ' || co.last_name)::text AS counselor_name,
       sts.sort_order AS time_slot_sort_order
FROM counselor_activity_explanations e
JOIN counselors co ON co.id = e.counselor_id
LEFT JOIN session_activities sa ON sa.id = e.session_activity_id
LEFT JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
WHERE e.solution_id = $1 AND e.camp_id = $2
ORDER BY co.last_name, co.first_name, e.explanation_type, COALESCE(e.constraint_name, ''), COALESCE(e.rank, 0), COALESCE(sts.sort_order, 0), e.message
`

type ListCounselorActivityExplanationsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorActivityExplanationsBySolutionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SolutionID         pgtype.UUID
	CounselorID        pgtype.UUID
	SessionActivityID  pgtype.UUID
	ExplanationType    string
	ConstraintName     pgtype.Text
	Rank               pgtype.Int4
	Message            string
	CounselorFirstName string
	CounselorLastName  string
	CounselorName      string
	TimeSlotSortOrder  pgtype.Int4
}

func (q *Queries) ListCounselorActivityExplanationsBySolution(ctx context.Context, arg ListCounselorActivityExplanationsBySolutionParams) ([]ListCounselorActivityExplanationsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityExplanationsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityExplanationsBySolutionRow
	for rows.Next() {
		var i ListCounselorActivityExplanationsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.SessionActivityID,
			&i.ExplanationType,
			&i.ConstraintName,
			&i.Rank,
			&i.Message,
			&i.CounselorFirstName,
			&i.CounselorLastName,
			&i.CounselorName,
			&i.TimeSlotSortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
