// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_cabin_solutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorCabinSolution = `-- name: CreateCounselorCabinSolution :one
INSERT INTO counselor_cabin_solutions (camp_id, assignment_run_id, solution_index, score, score_breakdown)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, assignment_run_id, solution_index, score, score_breakdown
`

type CreateCounselorCabinSolutionParams struct {
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

func (q *Queries) CreateCounselorCabinSolution(ctx context.Context, arg CreateCounselorCabinSolutionParams) (CounselorCabinSolution, error) {
	row := q.db.QueryRow(ctx, createCounselorCabinSolution,
		arg.CampID,
		arg.AssignmentRunID,
		arg.SolutionIndex,
		arg.Score,
		arg.ScoreBreakdown,
	)
	var i CounselorCabinSolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getCounselorCabinSolution = `-- name: GetCounselorCabinSolution :one
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM counselor_cabin_solutions
WHERE id = $1 AND camp_id = $2 AND assignment_run_id = $3
`

type GetCounselorCabinSolutionParams struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
}

func (q *Queries) GetCounselorCabinSolution(ctx context.Context, arg GetCounselorCabinSolutionParams) (CounselorCabinSolution, error) {
	row := q.db.QueryRow(ctx, getCounselorCabinSolution, arg.ID, arg.CampID, arg.AssignmentRunID)
	var i CounselorCabinSolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getSelectedCounselorCabinSolutionBySession = `-- name: GetSelectedCounselorCabinSolutionBySession :one
SELECT arss.solution_id
FROM assignment_runs ar
JOIN assignment_run_selected_solutions arss
    ON arss.run_id = ar.id AND arss.camp_id = ar.camp_id
WHERE ar.session_id = $1
    AND ar.camp_id = $2
    AND ar.run_type = 'counselor_cabin'
ORDER BY ar.created_at DESC
LIMIT 1
`

type GetSelectedCounselorCabinSolutionBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) GetSelectedCounselorCabinSolutionBySession(ctx context.Context, arg GetSelectedCounselorCabinSolutionBySessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSelectedCounselorCabinSolutionBySession, arg.SessionID, arg.CampID)
	var solution_id pgtype.UUID
	err := row.Scan(&solution_id)
	return solution_id, err
}

const listCounselorCabinSolutionsByRun = `-- name: ListCounselorCabinSolutionsByRun :many
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM counselor_cabin_solutions
WHERE assignment_run_id = $1 AND camp_id = $2
ORDER BY solution_index
`

type ListCounselorCabinSolutionsByRunParams struct {
	AssignmentRunID pgtype.UUID
	CampID          pgtype.UUID
}

func (q *Queries) ListCounselorCabinSolutionsByRun(ctx context.Context, arg ListCounselorCabinSolutionsByRunParams) ([]CounselorCabinSolution, error) {
	rows, err := q.db.Query(ctx, listCounselorCabinSolutionsByRun, arg.AssignmentRunID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorCabinSolution
	for rows.Next() {
		var i CounselorCabinSolution
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AssignmentRunID,
			&i.SolutionIndex,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
