// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_solutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivitySolution = `-- name: CreateCounselorActivitySolution :one
INSERT INTO counselor_activity_solutions (camp_id, assignment_run_id, solution_index, score, score_breakdown)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, assignment_run_id, solution_index, score, score_breakdown
`

type CreateCounselorActivitySolutionParams struct {
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

func (q *Queries) CreateCounselorActivitySolution(ctx context.Context, arg CreateCounselorActivitySolutionParams) (CounselorActivitySolution, error) {
	row := q.db.QueryRow(ctx, createCounselorActivitySolution,
		arg.CampID,
		arg.AssignmentRunID,
		arg.SolutionIndex,
		arg.Score,
		arg.ScoreBreakdown,
	)
	var i CounselorActivitySolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getCounselorActivitySolution = `-- name: GetCounselorActivitySolution :one
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM counselor_activity_solutions
WHERE id = $1 AND camp_id = $2 AND assignment_run_id = $3
`

type GetCounselorActivitySolutionParams struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
}

func (q *Queries) GetCounselorActivitySolution(ctx context.Context, arg GetCounselorActivitySolutionParams) (CounselorActivitySolution, error) {
	row := q.db.QueryRow(ctx, getCounselorActivitySolution, arg.ID, arg.CampID, arg.AssignmentRunID)
	var i CounselorActivitySolution
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.AssignmentRunID,
		&i.SolutionIndex,
		&i.Score,
		&i.ScoreBreakdown,
	)
	return i, err
}

const getSelectedCounselorActivitySolutionBySession = `-- name: GetSelectedCounselorActivitySolutionBySession :one
SELECT arss.solution_id
FROM assignment_runs ar
JOIN assignment_run_selected_solutions arss
    ON arss.run_id = ar.id AND arss.camp_id = ar.camp_id
WHERE ar.session_id = $1
    AND ar.camp_id = $2
    AND ar.run_type = 'activity_schedule'
ORDER BY ar.created_at DESC
LIMIT 1
`

type GetSelectedCounselorActivitySolutionBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) GetSelectedCounselorActivitySolutionBySession(ctx context.Context, arg GetSelectedCounselorActivitySolutionBySessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSelectedCounselorActivitySolutionBySession, arg.SessionID, arg.CampID)
	var solution_id pgtype.UUID
	err := row.Scan(&solution_id)
	return solution_id, err
}

const listCounselorActivitySolutionsByRun = `-- name: ListCounselorActivitySolutionsByRun :many
SELECT id, camp_id, assignment_run_id, solution_index, score, score_breakdown
FROM counselor_activity_solutions
WHERE assignment_run_id = $1 AND camp_id = $2
ORDER BY solution_index
`

type ListCounselorActivitySolutionsByRunParams struct {
	AssignmentRunID pgtype.UUID
	CampID          pgtype.UUID
}

func (q *Queries) ListCounselorActivitySolutionsByRun(ctx context.Context, arg ListCounselorActivitySolutionsByRunParams) ([]CounselorActivitySolution, error) {
	rows, err := q.db.Query(ctx, listCounselorActivitySolutionsByRun, arg.AssignmentRunID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorActivitySolution
	for rows.Next() {
		var i CounselorActivitySolution
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.AssignmentRunID,
			&i.SolutionIndex,
			&i.Score,
			&i.ScoreBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
