// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_unassigned.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivityUnassigned = `-- name: CreateCounselorActivityUnassigned :one
INSERT INTO counselor_activity_unassigned (camp_id, solution_id, counselor_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, solution_id, counselor_id
`

type CreateCounselorActivityUnassignedParams struct {
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) CreateCounselorActivityUnassigned(ctx context.Context, arg CreateCounselorActivityUnassignedParams) (CounselorActivityUnassigned, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityUnassigned, arg.CampID, arg.SolutionID, arg.CounselorID)
	var i CounselorActivityUnassigned
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SolutionID,
		&i.CounselorID,
	)
	return i, err
}

const createCounselorActivityUnassignedSlot = `-- name: CreateCounselorActivityUnassignedSlot :one
INSERT INTO counselor_activity_unassigned_slots (camp_id, unassigned_id, session_time_slot_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, unassigned_id, session_time_slot_id
`

type CreateCounselorActivityUnassignedSlotParams struct {
	CampID            pgtype.UUID
	UnassignedID      pgtype.UUID
	SessionTimeSlotID pgtype.UUID
}

func (q *Queries) CreateCounselorActivityUnassignedSlot(ctx context.Context, arg CreateCounselorActivityUnassignedSlotParams) (CounselorActivityUnassignedSlot, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityUnassignedSlot, arg.CampID, arg.UnassignedID, arg.SessionTimeSlotID)
	var i CounselorActivityUnassignedSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.UnassignedID,
		&i.SessionTimeSlotID,
	)
	return i, err
}

const listCounselorActivityUnassignedBySolution = `-- name: ListCounselorActivityUnassignedBySolution :many
SELECT u.id, u.camp_id, u.solution_id, u.counselor_id,
       (co.first_name || ' ' || co.last_name)::text AS counselor_name
FROM counselor_activity_unassigned u
JOIN counselors co ON co.id = u.counselor_id
WHERE u.solution_id = $1 AND u.camp_id = $2
ORDER BY co.last_name, co.first_name
`

type ListCounselorActivityUnassignedBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorActivityUnassignedBySolutionRow struct {
	ID            pgtype.UUID
	CampID        pgtype.UUID
	SolutionID    pgtype.UUID
	CounselorID   pgtype.UUID
	CounselorName string
}

func (q *Queries) ListCounselorActivityUnassignedBySolution(ctx context.Context, arg ListCounselorActivityUnassignedBySolutionParams) ([]ListCounselorActivityUnassignedBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityUnassignedBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityUnassignedBySolutionRow
	for rows.Next() {
		var i ListCounselorActivityUnassignedBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SolutionID,
			&i.CounselorID,
			&i.CounselorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounselorActivityUnassignedSlotsBySolution = `-- name: ListCounselorActivityUnassignedSlotsBySolution :many
SELECT s.id, s.camp_id, s.unassigned_id, s.session_time_slot_id,
       u.counselor_id,
       ts.time_slot_name AS time_slot_name,
       sts.sort_order AS sort_order
FROM counselor_activity_unassigned_slots s
JOIN counselor_activity_unassigned u ON u.id = s.unassigned_id
JOIN session_time_slots sts ON sts.id = s.session_time_slot_id
JOIN time_slots ts ON ts.id = sts.time_slot_id
WHERE u.solution_id = $1 AND s.camp_id = $2
ORDER BY u.counselor_id, sts.sort_order, ts.time_slot_name
`

type ListCounselorActivityUnassignedSlotsBySolutionParams struct {
	SolutionID pgtype.UUID
	CampID     pgtype.UUID
}

type ListCounselorActivityUnassignedSlotsBySolutionRow struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	UnassignedID      pgtype.UUID
	SessionTimeSlotID pgtype.UUID
	CounselorID       pgtype.UUID
	TimeSlotName      string
	SortOrder         int32
}

func (q *Queries) ListCounselorActivityUnassignedSlotsBySolution(ctx context.Context, arg ListCounselorActivityUnassignedSlotsBySolutionParams) ([]ListCounselorActivityUnassignedSlotsBySolutionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityUnassignedSlotsBySolution, arg.SolutionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityUnassignedSlotsBySolutionRow
	for rows.Next() {
		var i ListCounselorActivityUnassignedSlotsBySolutionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.UnassignedID,
			&i.SessionTimeSlotID,
			&i.CounselorID,
			&i.TimeSlotName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
