// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_activity_overrides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorActivityOverride = `-- name: CreateCounselorActivityOverride :one
INSERT INTO counselor_activity_overrides (camp_id, session_id, counselor_id, session_activity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, counselor_id, session_activity_id, created_at
`

type CreateCounselorActivityOverrideParams struct {
	CampID            pgtype.UUID
	SessionID         pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
}

func (q *Queries) CreateCounselorActivityOverride(ctx context.Context, arg CreateCounselorActivityOverrideParams) (CounselorActivityOverride, error) {
	row := q.db.QueryRow(ctx, createCounselorActivityOverride,
		arg.CampID,
		arg.SessionID,
		arg.CounselorID,
		arg.SessionActivityID,
	)
	var i CounselorActivityOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
		&i.SessionActivityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCounselorActivityOverride = `-- name: DeleteCounselorActivityOverride :execrows
DELETE FROM counselor_activity_overrides
WHERE id = $1 AND camp_id = $2
`

type DeleteCounselorActivityOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCounselorActivityOverride(ctx context.Context, arg DeleteCounselorActivityOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorActivityOverride, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselorActivityOverride = `-- name: GetCounselorActivityOverride :one
SELECT id, camp_id, session_id, counselor_id, session_activity_id, created_at
FROM counselor_activity_overrides
WHERE id = $1 AND camp_id = $2
`

type GetCounselorActivityOverrideParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCounselorActivityOverride(ctx context.Context, arg GetCounselorActivityOverrideParams) (CounselorActivityOverride, error) {
	row := q.db.QueryRow(ctx, getCounselorActivityOverride, arg.ID, arg.CampID)
	var i CounselorActivityOverride
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
		&i.SessionActivityID,
		&i.CreatedAt,
	)
	return i, err
}

const listCounselorActivityOverridesBySession = `-- name: ListCounselorActivityOverridesBySession :many
SELECT o.id, o.camp_id, o.session_id, o.counselor_id, o.session_activity_id, o.created_at,
       co.first_name AS counselor_first_name,
       co.last_name AS counselor_last_name,
       btrim(co.first_name || ' ' || co.last_name)::text AS counselor_name,
       sa.session_time_slot_id AS session_time_slot_id,
       act.activity_name AS activity_name,
       ts.time_slot_name AS time_slot_name,
       sts.sort_order AS sort_order
FROM counselor_activity_overrides o
JOIN counselors co ON co.id = o.counselor_id
JOIN session_activities sa ON sa.id = o.session_activity_id
JOIN activities act ON act.id = sa.activity_id
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
JOIN time_slots ts ON ts.id = sts.time_slot_id
WHERE o.session_id = $1 AND o.camp_id = $2
ORDER BY sts.sort_order, sts.id, act.activity_name, co.last_name, co.first_name
`

type ListCounselorActivityOverridesBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCounselorActivityOverridesBySessionRow struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	CounselorID        pgtype.UUID
	SessionActivityID  pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	CounselorFirstName string
	CounselorLastName  string
	CounselorName      string
	SessionTimeSlotID  pgtype.UUID
	ActivityName       string
	TimeSlotName       string
	SortOrder          int32
}

func (q *Queries) ListCounselorActivityOverridesBySession(ctx context.Context, arg ListCounselorActivityOverridesBySessionParams) ([]ListCounselorActivityOverridesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityOverridesBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityOverridesBySessionRow
	for rows.Next() {
		var i ListCounselorActivityOverridesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.CounselorID,
			&i.SessionActivityID,
			&i.CreatedAt,
			&i.CounselorFirstName,
			&i.CounselorLastName,
			&i.CounselorName,
			&i.SessionTimeSlotID,
			&i.ActivityName,
			&i.TimeSlotName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounselorActivityOverridesForSolver = `-- name: ListCounselorActivityOverridesForSolver :many
SELECT o.counselor_id, o.session_activity_id, sa.session_time_slot_id
FROM counselor_activity_overrides o
JOIN session_activities sa ON sa.id = o.session_activity_id
WHERE o.session_id = $1 AND o.camp_id = $2
`

type ListCounselorActivityOverridesForSolverParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListCounselorActivityOverridesForSolverRow struct {
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
	SessionTimeSlotID pgtype.UUID
}

func (q *Queries) ListCounselorActivityOverridesForSolver(ctx context.Context, arg ListCounselorActivityOverridesForSolverParams) ([]ListCounselorActivityOverridesForSolverRow, error) {
	rows, err := q.db.Query(ctx, listCounselorActivityOverridesForSolver, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorActivityOverridesForSolverRow
	for rows.Next() {
		var i ListCounselorActivityOverridesForSolverRow
		if err := rows.Scan(&i.CounselorID, &i.SessionActivityID, &i.SessionTimeSlotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
