// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselor = `-- name: CreateCounselor :one
INSERT INTO counselors (camp_id, first_name, last_name, junior_counselor, gender)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, first_name, last_name, junior_counselor, archived, gender
`

type CreateCounselorParams struct {
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Gender          string
}

type CreateCounselorRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) CreateCounselor(ctx context.Context, arg CreateCounselorParams) (CreateCounselorRow, error) {
	row := q.db.QueryRow(ctx, createCounselor,
		arg.CampID,
		arg.FirstName,
		arg.LastName,
		arg.JuniorCounselor,
		arg.Gender,
	)
	var i CreateCounselorRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.JuniorCounselor,
		&i.Archived,
		&i.Gender,
	)
	return i, err
}

const deleteCounselor = `-- name: DeleteCounselor :execrows
DELETE FROM counselors
WHERE id = $1 AND camp_id = $2
`

type DeleteCounselorParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCounselor(ctx context.Context, arg DeleteCounselorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselor, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselor = `-- name: GetCounselor :one
SELECT id, camp_id, first_name, last_name, junior_counselor, archived, gender
FROM counselors
WHERE id = $1 AND camp_id = $2
`

type GetCounselorParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

type GetCounselorRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) GetCounselor(ctx context.Context, arg GetCounselorParams) (GetCounselorRow, error) {
	row := q.db.QueryRow(ctx, getCounselor, arg.ID, arg.CampID)
	var i GetCounselorRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.JuniorCounselor,
		&i.Archived,
		&i.Gender,
	)
	return i, err
}

const listAllCounselors = `-- name: ListAllCounselors :many
SELECT id, camp_id, first_name, last_name, junior_counselor, archived, gender
FROM counselors
WHERE camp_id = $1
ORDER BY last_name, first_name
`

type ListAllCounselorsRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) ListAllCounselors(ctx context.Context, campID pgtype.UUID) ([]ListAllCounselorsRow, error) {
	rows, err := q.db.Query(ctx, listAllCounselors, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCounselorsRow
	for rows.Next() {
		var i ListAllCounselorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.JuniorCounselor,
			&i.Archived,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedCounselors = `-- name: ListArchivedCounselors :many
SELECT id, camp_id, first_name, last_name, junior_counselor, archived, gender
FROM counselors
WHERE camp_id = $1 AND archived = true
ORDER BY last_name, first_name
`

type ListArchivedCounselorsRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) ListArchivedCounselors(ctx context.Context, campID pgtype.UUID) ([]ListArchivedCounselorsRow, error) {
	rows, err := q.db.Query(ctx, listArchivedCounselors, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchivedCounselorsRow
	for rows.Next() {
		var i ListArchivedCounselorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.JuniorCounselor,
			&i.Archived,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounselors = `-- name: ListCounselors :many
SELECT id, camp_id, first_name, last_name, junior_counselor, archived, gender
FROM counselors
WHERE camp_id = $1 AND archived = false
ORDER BY last_name, first_name
`

type ListCounselorsRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) ListCounselors(ctx context.Context, campID pgtype.UUID) ([]ListCounselorsRow, error) {
	rows, err := q.db.Query(ctx, listCounselors, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselorsRow
	for rows.Next() {
		var i ListCounselorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.FirstName,
			&i.LastName,
			&i.JuniorCounselor,
			&i.Archived,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounselor = `-- name: UpdateCounselor :one
UPDATE counselors
SET first_name = $3,
    last_name = $4,
    junior_counselor = $5,
    gender = $6
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, first_name, last_name, junior_counselor, archived, gender
`

type UpdateCounselorParams struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Gender          string
}

type UpdateCounselorRow struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	FirstName       string
	LastName        string
	JuniorCounselor bool
	Archived        bool
	Gender          string
}

func (q *Queries) UpdateCounselor(ctx context.Context, arg UpdateCounselorParams) (UpdateCounselorRow, error) {
	row := q.db.QueryRow(ctx, updateCounselor,
		arg.ID,
		arg.CampID,
		arg.FirstName,
		arg.LastName,
		arg.JuniorCounselor,
		arg.Gender,
	)
	var i UpdateCounselorRow
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.FirstName,
		&i.LastName,
		&i.JuniorCounselor,
		&i.Archived,
		&i.Gender,
	)
	return i, err
}
