// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counselor_age_group_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounselorAgeGroupPreference = `-- name: CreateCounselorAgeGroupPreference :one
INSERT INTO counselor_age_group_preferences (camp_id, counselor_id, session_id, age_group_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, counselor_id, session_id, age_group_id, rank
`

type CreateCounselorAgeGroupPreferenceParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	Rank        int32
}

func (q *Queries) CreateCounselorAgeGroupPreference(ctx context.Context, arg CreateCounselorAgeGroupPreferenceParams) (CounselorAgeGroupPreference, error) {
	row := q.db.QueryRow(ctx, createCounselorAgeGroupPreference,
		arg.CampID,
		arg.CounselorID,
		arg.SessionID,
		arg.AgeGroupID,
		arg.Rank,
	)
	var i CounselorAgeGroupPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.Rank,
	)
	return i, err
}

const deleteCounselorAgeGroupPreference = `-- name: DeleteCounselorAgeGroupPreference :execrows
DELETE FROM counselor_age_group_preferences
WHERE id = $1 AND camp_id = $2
`

type DeleteCounselorAgeGroupPreferenceParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteCounselorAgeGroupPreference(ctx context.Context, arg DeleteCounselorAgeGroupPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounselorAgeGroupPreference, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselorAgeGroupPreference = `-- name: GetCounselorAgeGroupPreference :one
SELECT id, camp_id, counselor_id, session_id, age_group_id, rank
FROM counselor_age_group_preferences
WHERE id = $1 AND camp_id = $2
`

type GetCounselorAgeGroupPreferenceParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetCounselorAgeGroupPreference(ctx context.Context, arg GetCounselorAgeGroupPreferenceParams) (CounselorAgeGroupPreference, error) {
	row := q.db.QueryRow(ctx, getCounselorAgeGroupPreference, arg.ID, arg.CampID)
	var i CounselorAgeGroupPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.Rank,
	)
	return i, err
}

const listCounselorAgeGroupPreferences = `-- name: ListCounselorAgeGroupPreferences :many
SELECT id, camp_id, counselor_id, session_id, age_group_id, rank
FROM counselor_age_group_preferences
WHERE counselor_id = $1 AND session_id = $2 AND camp_id = $3
ORDER BY rank
`

type ListCounselorAgeGroupPreferencesParams struct {
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
}

func (q *Queries) ListCounselorAgeGroupPreferences(ctx context.Context, arg ListCounselorAgeGroupPreferencesParams) ([]CounselorAgeGroupPreference, error) {
	rows, err := q.db.Query(ctx, listCounselorAgeGroupPreferences, arg.CounselorID, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounselorAgeGroupPreference
	for rows.Next() {
		var i CounselorAgeGroupPreference
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.CounselorID,
			&i.SessionID,
			&i.AgeGroupID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounselorAgeGroupPreference = `-- name: UpdateCounselorAgeGroupPreference :one
UPDATE counselor_age_group_preferences
SET age_group_id = $3,
    rank = $4
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, counselor_id, session_id, age_group_id, rank
`

type UpdateCounselorAgeGroupPreferenceParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	AgeGroupID pgtype.UUID
	Rank       int32
}

func (q *Queries) UpdateCounselorAgeGroupPreference(ctx context.Context, arg UpdateCounselorAgeGroupPreferenceParams) (CounselorAgeGroupPreference, error) {
	row := q.db.QueryRow(ctx, updateCounselorAgeGroupPreference,
		arg.ID,
		arg.CampID,
		arg.AgeGroupID,
		arg.Rank,
	)
	var i CounselorAgeGroupPreference
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.CounselorID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.Rank,
	)
	return i, err
}
