// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	ActivityName string
	Archived     bool
}

type ActivityAssignment struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
}

type ActivityCertification struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	ActivityID      pgtype.UUID
	CertificationID pgtype.UUID
}

type ActivityExplanation struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	SolutionID        pgtype.UUID
	CounselorID       pgtype.UUID
	ExplanationType   string
	ConstraintName    pgtype.Text
	Message           string
	Rank              pgtype.Int4
	SessionActivityID pgtype.UUID
}

type ActivitySolution struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

type AgeGroup struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	AgeGroupName string
	Archived     bool
}

type AssignmentRun struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
	Status    string
	CreatedAt pgtype.Timestamptz
	IsStale   bool
}

type AssignmentRunSelectedSolution struct {
	CampID       pgtype.UUID
	RunID        pgtype.UUID
	SolutionID   pgtype.UUID
	SolutionType string
	SessionID    pgtype.UUID
}

type Cabin struct {
	ID                        pgtype.UUID
	CampID                    pgtype.UUID
	DefaultAgeGroupID         pgtype.UUID
	CabinName                 string
	DefaultGroupSize          int32
	DefaultRequiredCounselors int32
	Gender                    string
	Archived                  bool
}

type Camp struct {
	ID           pgtype.UUID
	CampName     string
	CampLocation pgtype.Text
	CampEnabled  bool
}

type Camper struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	Gender    string
	FirstName string
	LastName  string
	Archived  bool
}

type CamperCabinAssignment struct {
	ID                     pgtype.UUID
	CampID                 pgtype.UUID
	SolutionID             pgtype.UUID
	CamperID               pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
}

type CamperCabinExplanation struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CamperID        pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
	Rank            pgtype.Int4
}

type CamperCabinOverride struct {
	ID                     pgtype.UUID
	CampID                 pgtype.UUID
	SessionID              pgtype.UUID
	CamperID               pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

type CamperCabinSolution struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

type CamperFriendPreference struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	PreferredCamperID pgtype.UUID
	Rank              int32
}

type CamperSessionEnrollment struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	SessionAgeGroupID pgtype.UUID
}

type Certification struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CertificationName string
	Archived          bool
}

type Counselor struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	JuniorCounselor bool
	Gender          string
	FirstName       string
	LastName        string
	Archived        bool
}

type CounselorActivityOverride struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	SessionID         pgtype.UUID
	CounselorID       pgtype.UUID
	SessionActivityID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

type CounselorActivityPreference struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	ActivityID  pgtype.UUID
	Rank        int32
}

type CounselorActivityUnassigned struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
}

type CounselorActivityUnassignedSlot struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	UnassignedID      pgtype.UUID
	SessionTimeSlotID pgtype.UUID
}

type CounselorAgeGroupPreference struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	Rank        int32
}

type CounselorCabinAssignment struct {
	ID                     pgtype.UUID
	CampID                 pgtype.UUID
	SolutionID             pgtype.UUID
	CounselorID            pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
}

type CounselorCabinExplanation struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
	Rank            pgtype.Int4
}

type CounselorCabinOverride struct {
	ID                     pgtype.UUID
	CampID                 pgtype.UUID
	SessionID              pgtype.UUID
	CounselorID            pgtype.UUID
	SessionAgeGroupCabinID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

type CounselorCabinSolution struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

type CounselorCabinUnassigned struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
}

type CounselorCertification struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	CounselorID     pgtype.UUID
	CertificationID pgtype.UUID
}

type CounselorCocounselorPreference struct {
	ID                   pgtype.UUID
	CampID               pgtype.UUID
	CounselorID          pgtype.UUID
	SessionID            pgtype.UUID
	PreferredCounselorID pgtype.UUID
	Rank                 int32
}

type CounselorSessionHistory struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	CabinID     pgtype.UUID
}

type RefreshToken struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      string
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	TokenVersion   int32
	ImpersonatedBy pgtype.UUID
}

type Season struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SeasonName string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	Archived   bool
}

type Session struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SeasonID        pgtype.UUID
	SessionName     string
	PreviousSession pgtype.UUID
	Archived        bool
}

type SessionActivity struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionTimeSlotID  pgtype.UUID
	ActivityID         pgtype.UUID
	Capacity           int32
	RequiredCounselors int32
}

type SessionAgeGroup struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	AgeGroupID pgtype.UUID
}

type SessionAgeGroupCabin struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionAgeGroupID  pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
	Gender             string
}

type SessionCounselor struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SessionID   pgtype.UUID
	CounselorID pgtype.UUID
}

type SessionTimeSlot struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	TimeSlotID pgtype.UUID
	SortOrder  int32
}

type TimeSlot struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	TimeSlotName string
	Archived     bool
}

type User struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	TokenVersion int32
}
