// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgeGroup struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	AgeGroupName string
}

type Cabin struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	AgeGroupID pgtype.UUID
	CabinName  string
}

type Camp struct {
	ID           pgtype.UUID
	CampName     string
	CampLocation pgtype.Text
	CampEnabled  bool
}

type Counselor struct {
	ID               pgtype.UUID
	CampID           pgtype.UUID
	CounselorName    string
	JuniorCounselor  bool
	CounselorEnabled bool
}

type Season struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SeasonName string
}

type Session struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SeasonID        pgtype.UUID
	SessionName     string
	PreviousSession pgtype.UUID
}

type SessionAgeGroup struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	AgeGroupID pgtype.UUID
	GroupSize  pgtype.Int4
}

type SessionAgeGroupCabin struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionAgeGroupID  pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          pgtype.Int4
	RequiredCounselors pgtype.Int4
}
