// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	ActivityName string
}

type ActivityCertification struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	ActivityID      pgtype.UUID
	CertificationID pgtype.UUID
}

type AgeGroup struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	AgeGroupName string
}

type AssignmentRun struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	RunType   string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type AssignmentRunSelectedSolution struct {
	CampID       pgtype.UUID
	RunID        pgtype.UUID
	SolutionID   pgtype.UUID
	SolutionType string
}

type Cabin struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	AgeGroupID pgtype.UUID
	CabinName  string
}

type Camp struct {
	ID           pgtype.UUID
	CampName     string
	CampLocation pgtype.Text
	CampEnabled  bool
}

type Camper struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	CamperName string
}

type CamperCabinAssignment struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SolutionID pgtype.UUID
	CamperID   pgtype.UUID
	CabinID    pgtype.UUID
}

type CamperCabinExplanation struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CamperID        pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

type CamperCabinSolution struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

type CamperFriendPreference struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	PreferredCamperID pgtype.UUID
	Rank              int32
}

type CamperSessionEnrollment struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CamperID          pgtype.UUID
	SessionID         pgtype.UUID
	SessionAgeGroupID pgtype.UUID
}

type Certification struct {
	ID                pgtype.UUID
	CampID            pgtype.UUID
	CertificationName string
}

type Counselor struct {
	ID               pgtype.UUID
	CampID           pgtype.UUID
	CounselorName    string
	JuniorCounselor  bool
	CounselorEnabled bool
}

type CounselorAgeGroupPreference struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	Rank        int32
}

type CounselorCabinAssignment struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	SolutionID  pgtype.UUID
	CounselorID pgtype.UUID
	CabinID     pgtype.UUID
}

type CounselorCabinExplanation struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SolutionID      pgtype.UUID
	CounselorID     pgtype.UUID
	ExplanationType string
	ConstraintName  pgtype.Text
	Message         string
}

type CounselorCabinSolution struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	AssignmentRunID pgtype.UUID
	SolutionIndex   int32
	Score           float64
	ScoreBreakdown  []byte
}

type CounselorCocounselorPreference struct {
	ID                   pgtype.UUID
	CampID               pgtype.UUID
	CounselorID          pgtype.UUID
	SessionID            pgtype.UUID
	PreferredCounselorID pgtype.UUID
	Rank                 int32
}

type CounselorSessionHistory struct {
	ID          pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
	SessionID   pgtype.UUID
	AgeGroupID  pgtype.UUID
	CabinID     pgtype.UUID
}

type Season struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SeasonName string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

type Session struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SeasonID        pgtype.UUID
	SessionName     string
	PreviousSession pgtype.UUID
}

type SessionAgeGroup struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	AgeGroupID pgtype.UUID
	GroupSize  pgtype.Int4
}

type SessionAgeGroupCabin struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionAgeGroupID  pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          pgtype.Int4
	RequiredCounselors pgtype.Int4
}

type TimeSlot struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	TimeSlotName string
}
