// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (camp_id, season_name, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, season_name, start_date, end_date, archived
`

type CreateSeasonParams struct {
	CampID     pgtype.UUID
	SeasonName string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.CampID,
		arg.SeasonName,
		arg.StartDate,
		arg.EndDate,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonName,
		&i.StartDate,
		&i.EndDate,
		&i.Archived,
	)
	return i, err
}

const deleteSeason = `-- name: DeleteSeason :execrows
DELETE FROM seasons
WHERE id = $1 AND camp_id = $2
`

type DeleteSeasonParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteSeason(ctx context.Context, arg DeleteSeasonParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeason, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMostRecentSeason = `-- name: GetMostRecentSeason :one
SELECT id, camp_id, season_name, start_date, end_date, archived
FROM seasons
WHERE camp_id = $1
ORDER BY start_date DESC, id DESC
LIMIT 1
`

func (q *Queries) GetMostRecentSeason(ctx context.Context, campID pgtype.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, getMostRecentSeason, campID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonName,
		&i.StartDate,
		&i.EndDate,
		&i.Archived,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, camp_id, season_name, start_date, end_date, archived
FROM seasons
WHERE id = $1 AND camp_id = $2
`

type GetSeasonParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetSeason(ctx context.Context, arg GetSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, arg.ID, arg.CampID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonName,
		&i.StartDate,
		&i.EndDate,
		&i.Archived,
	)
	return i, err
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, camp_id, season_name, start_date, end_date, archived
FROM seasons
WHERE camp_id = $1
ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListSeasons(ctx context.Context, campID pgtype.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SeasonName,
			&i.StartDate,
			&i.EndDate,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE seasons
SET season_name = $3, start_date = $4, end_date = $5
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, season_name, start_date, end_date, archived
`

type UpdateSeasonParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SeasonName string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.ID,
		arg.CampID,
		arg.SeasonName,
		arg.StartDate,
		arg.EndDate,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonName,
		&i.StartDate,
		&i.EndDate,
		&i.Archived,
	)
	return i, err
}
