// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (camp_id, season_id, session_name, previous_session)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, season_id, session_name, previous_session
`

type CreateSessionParams struct {
	CampID          pgtype.UUID
	SeasonID        pgtype.UUID
	SessionName     string
	PreviousSession pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.CampID,
		arg.SeasonID,
		arg.SessionName,
		arg.PreviousSession,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonID,
		&i.SessionName,
		&i.PreviousSession,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1 AND camp_id = $2
`

type DeleteSessionParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT id, camp_id, season_id, session_name, previous_session
FROM sessions
WHERE id = $1 AND camp_id = $2
`

type GetSessionParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.CampID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonID,
		&i.SessionName,
		&i.PreviousSession,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, camp_id, season_id, session_name, previous_session
FROM sessions
WHERE camp_id = $1
ORDER BY session_name
`

func (q *Queries) ListSessions(ctx context.Context, campID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SeasonID,
			&i.SessionName,
			&i.PreviousSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET season_id = $3,
    session_name = $4,
    previous_session = $5
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, season_id, session_name, previous_session
`

type UpdateSessionParams struct {
	ID              pgtype.UUID
	CampID          pgtype.UUID
	SeasonID        pgtype.UUID
	SessionName     string
	PreviousSession pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.ID,
		arg.CampID,
		arg.SeasonID,
		arg.SessionName,
		arg.PreviousSession,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SeasonID,
		&i.SessionName,
		&i.PreviousSession,
	)
	return i, err
}
