// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_time_slots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionTimeSlot = `-- name: CreateSessionTimeSlot :one
INSERT INTO session_time_slots (camp_id, session_id, time_slot_id, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, time_slot_id, sort_order
`

type CreateSessionTimeSlotParams struct {
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	TimeSlotID pgtype.UUID
	SortOrder  int32
}

func (q *Queries) CreateSessionTimeSlot(ctx context.Context, arg CreateSessionTimeSlotParams) (SessionTimeSlot, error) {
	row := q.db.QueryRow(ctx, createSessionTimeSlot,
		arg.CampID,
		arg.SessionID,
		arg.TimeSlotID,
		arg.SortOrder,
	)
	var i SessionTimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.TimeSlotID,
		&i.SortOrder,
	)
	return i, err
}

const deleteSessionTimeSlot = `-- name: DeleteSessionTimeSlot :execrows
DELETE FROM session_time_slots
WHERE id = $1 AND camp_id = $2 AND session_id = $3
`

type DeleteSessionTimeSlotParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) DeleteSessionTimeSlot(ctx context.Context, arg DeleteSessionTimeSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionTimeSlot, arg.ID, arg.CampID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionTimeSlot = `-- name: GetSessionTimeSlot :one
SELECT id, camp_id, session_id, time_slot_id, sort_order
FROM session_time_slots
WHERE id = $1 AND camp_id = $2 AND session_id = $3
`

type GetSessionTimeSlotParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) GetSessionTimeSlot(ctx context.Context, arg GetSessionTimeSlotParams) (SessionTimeSlot, error) {
	row := q.db.QueryRow(ctx, getSessionTimeSlot, arg.ID, arg.CampID, arg.SessionID)
	var i SessionTimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.TimeSlotID,
		&i.SortOrder,
	)
	return i, err
}

const listSessionTimeSlots = `-- name: ListSessionTimeSlots :many
SELECT id, camp_id, session_id, time_slot_id, sort_order
FROM session_time_slots
WHERE session_id = $1 AND camp_id = $2
ORDER BY sort_order, time_slot_id
`

type ListSessionTimeSlotsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionTimeSlots(ctx context.Context, arg ListSessionTimeSlotsParams) ([]SessionTimeSlot, error) {
	rows, err := q.db.Query(ctx, listSessionTimeSlots, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionTimeSlot
	for rows.Next() {
		var i SessionTimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.TimeSlotID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionTimeSlot = `-- name: UpdateSessionTimeSlot :one
UPDATE session_time_slots
SET time_slot_id = $4,
    sort_order = $5
WHERE id = $1 AND camp_id = $2 AND session_id = $3
RETURNING id, camp_id, session_id, time_slot_id, sort_order
`

type UpdateSessionTimeSlotParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	TimeSlotID pgtype.UUID
	SortOrder  int32
}

func (q *Queries) UpdateSessionTimeSlot(ctx context.Context, arg UpdateSessionTimeSlotParams) (SessionTimeSlot, error) {
	row := q.db.QueryRow(ctx, updateSessionTimeSlot,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.TimeSlotID,
		arg.SortOrder,
	)
	var i SessionTimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.TimeSlotID,
		&i.SortOrder,
	)
	return i, err
}

const updateSessionTimeSlotSortOrder = `-- name: UpdateSessionTimeSlotSortOrder :exec
UPDATE session_time_slots
SET sort_order = $4
WHERE id = $1 AND camp_id = $2 AND session_id = $3
`

type UpdateSessionTimeSlotSortOrderParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
	SortOrder int32
}

func (q *Queries) UpdateSessionTimeSlotSortOrder(ctx context.Context, arg UpdateSessionTimeSlotSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateSessionTimeSlotSortOrder,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.SortOrder,
	)
	return err
}
