// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_age_group_cabins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSessionCabins = `-- name: ListSessionCabins :many
SELECT
    c.id,
    c.cabin_name,
    c.age_group_id,
    sagc.required_counselors
FROM session_age_groups sag
JOIN session_age_group_cabins sagc ON sagc.session_age_group_id = sag.id
JOIN cabins c ON c.id = sagc.cabin_id
WHERE sag.session_id = $1 AND sag.camp_id = $2
ORDER BY c.cabin_name
`

type ListSessionCabinsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCabinsRow struct {
	ID                 pgtype.UUID
	CabinName          string
	AgeGroupID         pgtype.UUID
	RequiredCounselors pgtype.Int4
}

func (q *Queries) ListSessionCabins(ctx context.Context, arg ListSessionCabinsParams) ([]ListSessionCabinsRow, error) {
	rows, err := q.db.Query(ctx, listSessionCabins, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCabinsRow
	for rows.Next() {
		var i ListSessionCabinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CabinName,
			&i.AgeGroupID,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
