// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_age_group_cabins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionAgeGroupCabin = `-- name: CreateSessionAgeGroupCabin :one
INSERT INTO session_age_group_cabins (camp_id, session_age_group_id, cabin_id, group_size, required_counselors)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, session_age_group_id, cabin_id, group_size, required_counselors
`

type CreateSessionAgeGroupCabinParams struct {
	CampID             pgtype.UUID
	SessionAgeGroupID  pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
}

func (q *Queries) CreateSessionAgeGroupCabin(ctx context.Context, arg CreateSessionAgeGroupCabinParams) (SessionAgeGroupCabin, error) {
	row := q.db.QueryRow(ctx, createSessionAgeGroupCabin,
		arg.CampID,
		arg.SessionAgeGroupID,
		arg.CabinID,
		arg.GroupSize,
		arg.RequiredCounselors,
	)
	var i SessionAgeGroupCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
	)
	return i, err
}

const deleteSessionAgeGroupCabin = `-- name: DeleteSessionAgeGroupCabin :execrows
DELETE FROM session_age_group_cabins sagc
USING session_age_groups sag
WHERE sagc.id = $1 AND sagc.camp_id = $2
  AND sag.id = sagc.session_age_group_id AND sag.session_id = $3
`

type DeleteSessionAgeGroupCabinParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) DeleteSessionAgeGroupCabin(ctx context.Context, arg DeleteSessionAgeGroupCabinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionAgeGroupCabin, arg.ID, arg.CampID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionAgeGroupCabin = `-- name: GetSessionAgeGroupCabin :one
SELECT sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors
FROM session_age_group_cabins sagc
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
WHERE sagc.id = $1 AND sagc.camp_id = $2 AND sag.session_id = $3
`

type GetSessionAgeGroupCabinParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) GetSessionAgeGroupCabin(ctx context.Context, arg GetSessionAgeGroupCabinParams) (SessionAgeGroupCabin, error) {
	row := q.db.QueryRow(ctx, getSessionAgeGroupCabin, arg.ID, arg.CampID, arg.SessionID)
	var i SessionAgeGroupCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
	)
	return i, err
}

const listSessionAgeGroupCabins = `-- name: ListSessionAgeGroupCabins :many
SELECT id, camp_id, session_age_group_id, cabin_id, group_size, required_counselors
FROM session_age_group_cabins
WHERE session_age_group_id = $1 AND camp_id = $2
ORDER BY cabin_id
`

type ListSessionAgeGroupCabinsParams struct {
	SessionAgeGroupID pgtype.UUID
	CampID            pgtype.UUID
}

func (q *Queries) ListSessionAgeGroupCabins(ctx context.Context, arg ListSessionAgeGroupCabinsParams) ([]SessionAgeGroupCabin, error) {
	rows, err := q.db.Query(ctx, listSessionAgeGroupCabins, arg.SessionAgeGroupID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAgeGroupCabin
	for rows.Next() {
		var i SessionAgeGroupCabin
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionAgeGroupID,
			&i.CabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAgeGroupCabinsBySession = `-- name: ListSessionAgeGroupCabinsBySession :many
SELECT sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors
FROM session_age_group_cabins sagc
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
WHERE sag.session_id = $1 AND sagc.camp_id = $2
ORDER BY sagc.cabin_id
`

type ListSessionAgeGroupCabinsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionAgeGroupCabinsBySession(ctx context.Context, arg ListSessionAgeGroupCabinsBySessionParams) ([]SessionAgeGroupCabin, error) {
	rows, err := q.db.Query(ctx, listSessionAgeGroupCabinsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAgeGroupCabin
	for rows.Next() {
		var i SessionAgeGroupCabin
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionAgeGroupID,
			&i.CabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCabins = `-- name: ListSessionCabins :many
SELECT
    c.id,
    c.cabin_name,
    c.gender,
    sag.age_group_id,
    ag.age_group_name,
    sagc.id AS session_age_group_cabin_id,
    sagc.required_counselors
FROM session_age_groups sag
JOIN session_age_group_cabins sagc ON sagc.session_age_group_id = sag.id
JOIN cabins c ON c.id = sagc.cabin_id
JOIN age_groups ag ON ag.id = sag.age_group_id
WHERE sag.session_id = $1 AND sag.camp_id = $2
ORDER BY c.cabin_name
`

type ListSessionCabinsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCabinsRow struct {
	ID                     pgtype.UUID
	CabinName              string
	Gender                 string
	AgeGroupID             pgtype.UUID
	AgeGroupName           string
	SessionAgeGroupCabinID pgtype.UUID
	RequiredCounselors     int32
}

func (q *Queries) ListSessionCabins(ctx context.Context, arg ListSessionCabinsParams) ([]ListSessionCabinsRow, error) {
	rows, err := q.db.Query(ctx, listSessionCabins, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCabinsRow
	for rows.Next() {
		var i ListSessionCabinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CabinName,
			&i.Gender,
			&i.AgeGroupID,
			&i.AgeGroupName,
			&i.SessionAgeGroupCabinID,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCabinsWithCapacity = `-- name: ListSessionCabinsWithCapacity :many
SELECT
    c.id,
    c.cabin_name,
    c.gender,
    c.archived AS cabin_archived,
    sag.age_group_id,
    ag.age_group_name,
    ag.archived AS age_group_archived,
    sagc.id AS session_age_group_cabin_id,
    sagc.group_size,
    sagc.required_counselors
FROM session_age_groups sag
JOIN session_age_group_cabins sagc ON sagc.session_age_group_id = sag.id
JOIN cabins c ON c.id = sagc.cabin_id
JOIN age_groups ag ON ag.id = sag.age_group_id AND ag.camp_id = sag.camp_id
WHERE sag.session_id = $1 AND sag.camp_id = $2
ORDER BY c.cabin_name
`

type ListSessionCabinsWithCapacityParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCabinsWithCapacityRow struct {
	ID                     pgtype.UUID
	CabinName              string
	Gender                 string
	CabinArchived          bool
	AgeGroupID             pgtype.UUID
	AgeGroupName           string
	AgeGroupArchived       bool
	SessionAgeGroupCabinID pgtype.UUID
	GroupSize              int32
	RequiredCounselors     int32
}

func (q *Queries) ListSessionCabinsWithCapacity(ctx context.Context, arg ListSessionCabinsWithCapacityParams) ([]ListSessionCabinsWithCapacityRow, error) {
	rows, err := q.db.Query(ctx, listSessionCabinsWithCapacity, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCabinsWithCapacityRow
	for rows.Next() {
		var i ListSessionCabinsWithCapacityRow
		if err := rows.Scan(
			&i.ID,
			&i.CabinName,
			&i.Gender,
			&i.CabinArchived,
			&i.AgeGroupID,
			&i.AgeGroupName,
			&i.AgeGroupArchived,
			&i.SessionAgeGroupCabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAgeGroupCabin = `-- name: UpdateSessionAgeGroupCabin :one
UPDATE session_age_group_cabins sagc
SET cabin_id = $4,
    group_size = $5,
    required_counselors = $6
FROM session_age_groups sag
WHERE sagc.id = $1 AND sagc.camp_id = $2
  AND sag.id = sagc.session_age_group_id AND sag.session_id = $3
RETURNING sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors
`

type UpdateSessionAgeGroupCabinParams struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
}

func (q *Queries) UpdateSessionAgeGroupCabin(ctx context.Context, arg UpdateSessionAgeGroupCabinParams) (SessionAgeGroupCabin, error) {
	row := q.db.QueryRow(ctx, updateSessionAgeGroupCabin,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.CabinID,
		arg.GroupSize,
		arg.RequiredCounselors,
	)
	var i SessionAgeGroupCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
	)
	return i, err
}
