// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionActivity = `-- name: CreateSessionActivity :one
INSERT INTO session_activities (camp_id, session_time_slot_id, activity_id, capacity, required_counselors)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, camp_id, session_time_slot_id, activity_id, capacity, required_counselors
`

type CreateSessionActivityParams struct {
	CampID             pgtype.UUID
	SessionTimeSlotID  pgtype.UUID
	ActivityID         pgtype.UUID
	Capacity           int32
	RequiredCounselors int32
}

func (q *Queries) CreateSessionActivity(ctx context.Context, arg CreateSessionActivityParams) (SessionActivity, error) {
	row := q.db.QueryRow(ctx, createSessionActivity,
		arg.CampID,
		arg.SessionTimeSlotID,
		arg.ActivityID,
		arg.Capacity,
		arg.RequiredCounselors,
	)
	var i SessionActivity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionTimeSlotID,
		&i.ActivityID,
		&i.Capacity,
		&i.RequiredCounselors,
	)
	return i, err
}

const deleteSessionActivity = `-- name: DeleteSessionActivity :execrows
DELETE FROM session_activities sa
USING session_time_slots sts
WHERE sa.id = $1 AND sa.camp_id = $2
  AND sts.id = sa.session_time_slot_id AND sts.session_id = $3
`

type DeleteSessionActivityParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) DeleteSessionActivity(ctx context.Context, arg DeleteSessionActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionActivity, arg.ID, arg.CampID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionActivity = `-- name: GetSessionActivity :one
SELECT sa.id, sa.camp_id, sa.session_time_slot_id, sa.activity_id, sa.capacity, sa.required_counselors
FROM session_activities sa
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
WHERE sa.id = $1 AND sa.camp_id = $2 AND sts.session_id = $3
`

type GetSessionActivityParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) GetSessionActivity(ctx context.Context, arg GetSessionActivityParams) (SessionActivity, error) {
	row := q.db.QueryRow(ctx, getSessionActivity, arg.ID, arg.CampID, arg.SessionID)
	var i SessionActivity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionTimeSlotID,
		&i.ActivityID,
		&i.Capacity,
		&i.RequiredCounselors,
	)
	return i, err
}

const listActivityCertificationsBySession = `-- name: ListActivityCertificationsBySession :many
SELECT
    sa.id AS session_activity_id,
    ac.certification_id
FROM session_activities sa
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
JOIN activity_certifications ac ON ac.activity_id = sa.activity_id AND ac.camp_id = sa.camp_id
WHERE sts.session_id = $1 AND sa.camp_id = $2
ORDER BY sa.id, ac.certification_id
`

type ListActivityCertificationsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListActivityCertificationsBySessionRow struct {
	SessionActivityID pgtype.UUID
	CertificationID   pgtype.UUID
}

func (q *Queries) ListActivityCertificationsBySession(ctx context.Context, arg ListActivityCertificationsBySessionParams) ([]ListActivityCertificationsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listActivityCertificationsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityCertificationsBySessionRow
	for rows.Next() {
		var i ListActivityCertificationsBySessionRow
		if err := rows.Scan(&i.SessionActivityID, &i.CertificationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionActivities = `-- name: ListSessionActivities :many
SELECT sa.id, sa.camp_id, sa.session_time_slot_id, sa.activity_id, sa.capacity, sa.required_counselors
FROM session_activities sa
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
WHERE sts.session_id = $1 AND sa.camp_id = $2
ORDER BY sts.sort_order, sa.activity_id
`

type ListSessionActivitiesParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionActivities(ctx context.Context, arg ListSessionActivitiesParams) ([]SessionActivity, error) {
	rows, err := q.db.Query(ctx, listSessionActivities, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionActivity
	for rows.Next() {
		var i SessionActivity
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionTimeSlotID,
			&i.ActivityID,
			&i.Capacity,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionActivitiesByTimeSlot = `-- name: ListSessionActivitiesByTimeSlot :many
SELECT id, camp_id, session_time_slot_id, activity_id, capacity, required_counselors
FROM session_activities
WHERE session_time_slot_id = $1 AND camp_id = $2
ORDER BY activity_id
`

type ListSessionActivitiesByTimeSlotParams struct {
	SessionTimeSlotID pgtype.UUID
	CampID            pgtype.UUID
}

func (q *Queries) ListSessionActivitiesByTimeSlot(ctx context.Context, arg ListSessionActivitiesByTimeSlotParams) ([]SessionActivity, error) {
	rows, err := q.db.Query(ctx, listSessionActivitiesByTimeSlot, arg.SessionTimeSlotID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionActivity
	for rows.Next() {
		var i SessionActivity
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionTimeSlotID,
			&i.ActivityID,
			&i.Capacity,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionActivitiesWithDetails = `-- name: ListSessionActivitiesWithDetails :many
SELECT
    sa.id AS session_activity_id,
    sa.capacity,
    sa.required_counselors,
    a.id AS activity_id,
    a.activity_name,
    sts.id AS session_time_slot_id,
    sts.time_slot_id,
    ts.time_slot_name,
    sts.sort_order
FROM session_activities sa
JOIN activities a ON a.id = sa.activity_id
JOIN session_time_slots sts ON sts.id = sa.session_time_slot_id
JOIN time_slots ts ON ts.id = sts.time_slot_id
WHERE sts.session_id = $1 AND sa.camp_id = $2
ORDER BY sts.sort_order, a.activity_name
`

type ListSessionActivitiesWithDetailsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionActivitiesWithDetailsRow struct {
	SessionActivityID  pgtype.UUID
	Capacity           int32
	RequiredCounselors int32
	ActivityID         pgtype.UUID
	ActivityName       string
	SessionTimeSlotID  pgtype.UUID
	TimeSlotID         pgtype.UUID
	TimeSlotName       string
	SortOrder          int32
}

func (q *Queries) ListSessionActivitiesWithDetails(ctx context.Context, arg ListSessionActivitiesWithDetailsParams) ([]ListSessionActivitiesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSessionActivitiesWithDetails, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionActivitiesWithDetailsRow
	for rows.Next() {
		var i ListSessionActivitiesWithDetailsRow
		if err := rows.Scan(
			&i.SessionActivityID,
			&i.Capacity,
			&i.RequiredCounselors,
			&i.ActivityID,
			&i.ActivityName,
			&i.SessionTimeSlotID,
			&i.TimeSlotID,
			&i.TimeSlotName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionActivity = `-- name: UpdateSessionActivity :one
UPDATE session_activities sa
SET activity_id = $4,
    capacity = $5,
    required_counselors = $6
FROM session_time_slots sts
WHERE sa.id = $1 AND sa.camp_id = $2
  AND sts.id = sa.session_time_slot_id AND sts.session_id = $3
RETURNING sa.id, sa.camp_id, sa.session_time_slot_id, sa.activity_id, sa.capacity, sa.required_counselors
`

type UpdateSessionActivityParams struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	ActivityID         pgtype.UUID
	Capacity           int32
	RequiredCounselors int32
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) (SessionActivity, error) {
	row := q.db.QueryRow(ctx, updateSessionActivity,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.ActivityID,
		arg.Capacity,
		arg.RequiredCounselors,
	)
	var i SessionActivity
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionTimeSlotID,
		&i.ActivityID,
		&i.Capacity,
		&i.RequiredCounselors,
	)
	return i, err
}
