// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_age_groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionAgeGroup = `-- name: CreateSessionAgeGroup :one
INSERT INTO session_age_groups (camp_id, session_id, age_group_id, group_size)
VALUES ($1, $2, $3, $4)
RETURNING id, camp_id, session_id, age_group_id, group_size
`

type CreateSessionAgeGroupParams struct {
	CampID     pgtype.UUID
	SessionID  pgtype.UUID
	AgeGroupID pgtype.UUID
	GroupSize  pgtype.Int4
}

func (q *Queries) CreateSessionAgeGroup(ctx context.Context, arg CreateSessionAgeGroupParams) (SessionAgeGroup, error) {
	row := q.db.QueryRow(ctx, createSessionAgeGroup,
		arg.CampID,
		arg.SessionID,
		arg.AgeGroupID,
		arg.GroupSize,
	)
	var i SessionAgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.GroupSize,
	)
	return i, err
}

const deleteSessionAgeGroup = `-- name: DeleteSessionAgeGroup :execrows
DELETE FROM session_age_groups
WHERE id = $1 AND camp_id = $2
`

type DeleteSessionAgeGroupParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteSessionAgeGroup(ctx context.Context, arg DeleteSessionAgeGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionAgeGroup, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionAgeGroup = `-- name: GetSessionAgeGroup :one
SELECT id, camp_id, session_id, age_group_id, group_size
FROM session_age_groups
WHERE id = $1 AND camp_id = $2
`

type GetSessionAgeGroupParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetSessionAgeGroup(ctx context.Context, arg GetSessionAgeGroupParams) (SessionAgeGroup, error) {
	row := q.db.QueryRow(ctx, getSessionAgeGroup, arg.ID, arg.CampID)
	var i SessionAgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.GroupSize,
	)
	return i, err
}

const listSessionAgeGroups = `-- name: ListSessionAgeGroups :many
SELECT id, camp_id, session_id, age_group_id, group_size
FROM session_age_groups
WHERE session_id = $1 AND camp_id = $2
ORDER BY age_group_id
`

type ListSessionAgeGroupsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionAgeGroups(ctx context.Context, arg ListSessionAgeGroupsParams) ([]SessionAgeGroup, error) {
	rows, err := q.db.Query(ctx, listSessionAgeGroups, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAgeGroup
	for rows.Next() {
		var i SessionAgeGroup
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.AgeGroupID,
			&i.GroupSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAgeGroup = `-- name: UpdateSessionAgeGroup :one
UPDATE session_age_groups
SET age_group_id = $3,
    group_size = $4
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, session_id, age_group_id, group_size
`

type UpdateSessionAgeGroupParams struct {
	ID         pgtype.UUID
	CampID     pgtype.UUID
	AgeGroupID pgtype.UUID
	GroupSize  pgtype.Int4
}

func (q *Queries) UpdateSessionAgeGroup(ctx context.Context, arg UpdateSessionAgeGroupParams) (SessionAgeGroup, error) {
	row := q.db.QueryRow(ctx, updateSessionAgeGroup,
		arg.ID,
		arg.CampID,
		arg.AgeGroupID,
		arg.GroupSize,
	)
	var i SessionAgeGroup
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.AgeGroupID,
		&i.GroupSize,
	)
	return i, err
}
