// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_counselors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSessionCounselor = `-- name: AddSessionCounselor :one
INSERT INTO session_counselors (camp_id, session_id, counselor_id)
VALUES ($1, $2, $3)
RETURNING id, camp_id, session_id, counselor_id
`

type AddSessionCounselorParams struct {
	CampID      pgtype.UUID
	SessionID   pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) AddSessionCounselor(ctx context.Context, arg AddSessionCounselorParams) (SessionCounselor, error) {
	row := q.db.QueryRow(ctx, addSessionCounselor, arg.CampID, arg.SessionID, arg.CounselorID)
	var i SessionCounselor
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
	)
	return i, err
}

const deleteAllSessionCounselors = `-- name: DeleteAllSessionCounselors :exec
DELETE FROM session_counselors
WHERE session_id = $1 AND camp_id = $2
`

type DeleteAllSessionCounselorsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) DeleteAllSessionCounselors(ctx context.Context, arg DeleteAllSessionCounselorsParams) error {
	_, err := q.db.Exec(ctx, deleteAllSessionCounselors, arg.SessionID, arg.CampID)
	return err
}

const getSessionCounselor = `-- name: GetSessionCounselor :one
SELECT id, camp_id, session_id, counselor_id
FROM session_counselors
WHERE session_id = $1 AND camp_id = $2 AND counselor_id = $3
`

type GetSessionCounselorParams struct {
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) GetSessionCounselor(ctx context.Context, arg GetSessionCounselorParams) (SessionCounselor, error) {
	row := q.db.QueryRow(ctx, getSessionCounselor, arg.SessionID, arg.CampID, arg.CounselorID)
	var i SessionCounselor
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionID,
		&i.CounselorID,
	)
	return i, err
}

const isCounselorInSession = `-- name: IsCounselorInSession :one
SELECT EXISTS (
    SELECT 1 FROM session_counselors
    WHERE session_id = $1 AND camp_id = $2 AND counselor_id = $3
) AS exists
`

type IsCounselorInSessionParams struct {
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) IsCounselorInSession(ctx context.Context, arg IsCounselorInSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCounselorInSession, arg.SessionID, arg.CampID, arg.CounselorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSessionCounselorIDs = `-- name: ListSessionCounselorIDs :many
SELECT counselor_id
FROM session_counselors
WHERE session_id = $1 AND camp_id = $2
`

type ListSessionCounselorIDsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionCounselorIDs(ctx context.Context, arg ListSessionCounselorIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionCounselorIDs, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var counselor_id pgtype.UUID
		if err := rows.Scan(&counselor_id); err != nil {
			return nil, err
		}
		items = append(items, counselor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCounselors = `-- name: ListSessionCounselors :many
SELECT sc.id, sc.camp_id, sc.session_id, sc.counselor_id,
       c.counselor_name, c.junior_counselor, c.counselor_enabled, c.gender
FROM session_counselors sc
JOIN counselors c ON c.id = sc.counselor_id AND c.camp_id = sc.camp_id
WHERE sc.session_id = $1 AND sc.camp_id = $2
ORDER BY c.counselor_name
`

type ListSessionCounselorsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCounselorsRow struct {
	ID               pgtype.UUID
	CampID           pgtype.UUID
	SessionID        pgtype.UUID
	CounselorID      pgtype.UUID
	CounselorName    string
	JuniorCounselor  bool
	CounselorEnabled bool
	Gender           string
}

func (q *Queries) ListSessionCounselors(ctx context.Context, arg ListSessionCounselorsParams) ([]ListSessionCounselorsRow, error) {
	rows, err := q.db.Query(ctx, listSessionCounselors, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCounselorsRow
	for rows.Next() {
		var i ListSessionCounselorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionID,
			&i.CounselorID,
			&i.CounselorName,
			&i.JuniorCounselor,
			&i.CounselorEnabled,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCounselorFromAllSessions = `-- name: RemoveCounselorFromAllSessions :exec
DELETE FROM session_counselors
WHERE camp_id = $1 AND counselor_id = $2
`

type RemoveCounselorFromAllSessionsParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) RemoveCounselorFromAllSessions(ctx context.Context, arg RemoveCounselorFromAllSessionsParams) error {
	_, err := q.db.Exec(ctx, removeCounselorFromAllSessions, arg.CampID, arg.CounselorID)
	return err
}

const removeSessionCounselor = `-- name: RemoveSessionCounselor :execrows
DELETE FROM session_counselors
WHERE session_id = $1 AND camp_id = $2 AND counselor_id = $3
`

type RemoveSessionCounselorParams struct {
	SessionID   pgtype.UUID
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) RemoveSessionCounselor(ctx context.Context, arg RemoveSessionCounselorParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSessionCounselor, arg.SessionID, arg.CampID, arg.CounselorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
