// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_cabins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionCabin = `-- name: CreateSessionCabin :one
INSERT INTO session_cabins (camp_id, session_age_group_id, cabin_id, group_size, required_counselors, gender)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, camp_id, session_age_group_id, cabin_id, group_size, required_counselors, gender
`

type CreateSessionCabinParams struct {
	CampID             pgtype.UUID
	SessionAgeGroupID  pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
	Gender             string
}

func (q *Queries) CreateSessionCabin(ctx context.Context, arg CreateSessionCabinParams) (SessionCabin, error) {
	row := q.db.QueryRow(ctx, createSessionCabin,
		arg.CampID,
		arg.SessionAgeGroupID,
		arg.CabinID,
		arg.GroupSize,
		arg.RequiredCounselors,
		arg.Gender,
	)
	var i SessionCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
		&i.Gender,
	)
	return i, err
}

const deleteSessionCabin = `-- name: DeleteSessionCabin :execrows
DELETE FROM session_cabins sagc
USING session_age_groups sag
WHERE sagc.id = $1 AND sagc.camp_id = $2
  AND sag.id = sagc.session_age_group_id AND sag.session_id = $3
`

type DeleteSessionCabinParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) DeleteSessionCabin(ctx context.Context, arg DeleteSessionCabinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionCabin, arg.ID, arg.CampID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionCabin = `-- name: GetSessionCabin :one
SELECT sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors, sagc.gender
FROM session_cabins sagc
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
WHERE sagc.id = $1 AND sagc.camp_id = $2 AND sag.session_id = $3
`

type GetSessionCabinParams struct {
	ID        pgtype.UUID
	CampID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) GetSessionCabin(ctx context.Context, arg GetSessionCabinParams) (SessionCabin, error) {
	row := q.db.QueryRow(ctx, getSessionCabin, arg.ID, arg.CampID, arg.SessionID)
	var i SessionCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
		&i.Gender,
	)
	return i, err
}

const listSessionCabins = `-- name: ListSessionCabins :many
SELECT
    c.id,
    c.cabin_name,
    sagc.gender,
    sag.age_group_id,
    ag.age_group_name,
    sagc.id AS session_cabin_id,
    sagc.required_counselors
FROM session_age_groups sag
JOIN session_cabins sagc ON sagc.session_age_group_id = sag.id
JOIN cabins c ON c.id = sagc.cabin_id
JOIN age_groups ag ON ag.id = sag.age_group_id
WHERE sag.session_id = $1 AND sag.camp_id = $2
ORDER BY c.cabin_name
`

type ListSessionCabinsParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCabinsRow struct {
	ID                 pgtype.UUID
	CabinName          string
	Gender             string
	AgeGroupID         pgtype.UUID
	AgeGroupName       string
	SessionCabinID     pgtype.UUID
	RequiredCounselors int32
}

func (q *Queries) ListSessionCabins(ctx context.Context, arg ListSessionCabinsParams) ([]ListSessionCabinsRow, error) {
	rows, err := q.db.Query(ctx, listSessionCabins, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCabinsRow
	for rows.Next() {
		var i ListSessionCabinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CabinName,
			&i.Gender,
			&i.AgeGroupID,
			&i.AgeGroupName,
			&i.SessionCabinID,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCabinsBySession = `-- name: ListSessionCabinsBySession :many
SELECT sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors, sagc.gender
FROM session_cabins sagc
JOIN session_age_groups sag ON sag.id = sagc.session_age_group_id
WHERE sag.session_id = $1 AND sagc.camp_id = $2
ORDER BY sagc.cabin_id
`

type ListSessionCabinsBySessionParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

func (q *Queries) ListSessionCabinsBySession(ctx context.Context, arg ListSessionCabinsBySessionParams) ([]SessionCabin, error) {
	rows, err := q.db.Query(ctx, listSessionCabinsBySession, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionCabin
	for rows.Next() {
		var i SessionCabin
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionAgeGroupID,
			&i.CabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCabinsRaw = `-- name: ListSessionCabinsRaw :many
SELECT id, camp_id, session_age_group_id, cabin_id, group_size, required_counselors, gender
FROM session_cabins
WHERE session_age_group_id = $1 AND camp_id = $2
ORDER BY cabin_id
`

type ListSessionCabinsRawParams struct {
	SessionAgeGroupID pgtype.UUID
	CampID            pgtype.UUID
}

func (q *Queries) ListSessionCabinsRaw(ctx context.Context, arg ListSessionCabinsRawParams) ([]SessionCabin, error) {
	rows, err := q.db.Query(ctx, listSessionCabinsRaw, arg.SessionAgeGroupID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionCabin
	for rows.Next() {
		var i SessionCabin
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SessionAgeGroupID,
			&i.CabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCabinsWithCapacity = `-- name: ListSessionCabinsWithCapacity :many
SELECT
    c.id,
    c.cabin_name,
    sagc.gender,
    c.archived AS cabin_archived,
    sag.age_group_id,
    ag.age_group_name,
    ag.archived AS age_group_archived,
    sagc.id AS session_cabin_id,
    sagc.group_size,
    sagc.required_counselors
FROM session_age_groups sag
JOIN session_cabins sagc ON sagc.session_age_group_id = sag.id
JOIN cabins c ON c.id = sagc.cabin_id
JOIN age_groups ag ON ag.id = sag.age_group_id AND ag.camp_id = sag.camp_id
WHERE sag.session_id = $1 AND sag.camp_id = $2
ORDER BY c.cabin_name
`

type ListSessionCabinsWithCapacityParams struct {
	SessionID pgtype.UUID
	CampID    pgtype.UUID
}

type ListSessionCabinsWithCapacityRow struct {
	ID                 pgtype.UUID
	CabinName          string
	Gender             string
	CabinArchived      bool
	AgeGroupID         pgtype.UUID
	AgeGroupName       string
	AgeGroupArchived   bool
	SessionCabinID     pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
}

func (q *Queries) ListSessionCabinsWithCapacity(ctx context.Context, arg ListSessionCabinsWithCapacityParams) ([]ListSessionCabinsWithCapacityRow, error) {
	rows, err := q.db.Query(ctx, listSessionCabinsWithCapacity, arg.SessionID, arg.CampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCabinsWithCapacityRow
	for rows.Next() {
		var i ListSessionCabinsWithCapacityRow
		if err := rows.Scan(
			&i.ID,
			&i.CabinName,
			&i.Gender,
			&i.CabinArchived,
			&i.AgeGroupID,
			&i.AgeGroupName,
			&i.AgeGroupArchived,
			&i.SessionCabinID,
			&i.GroupSize,
			&i.RequiredCounselors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionCabin = `-- name: UpdateSessionCabin :one
UPDATE session_cabins sagc
SET cabin_id = $4,
    group_size = $5,
    required_counselors = $6,
    gender = $7
FROM session_age_groups sag
WHERE sagc.id = $1 AND sagc.camp_id = $2
  AND sag.id = sagc.session_age_group_id AND sag.session_id = $3
RETURNING sagc.id, sagc.camp_id, sagc.session_age_group_id, sagc.cabin_id, sagc.group_size, sagc.required_counselors, sagc.gender
`

type UpdateSessionCabinParams struct {
	ID                 pgtype.UUID
	CampID             pgtype.UUID
	SessionID          pgtype.UUID
	CabinID            pgtype.UUID
	GroupSize          int32
	RequiredCounselors int32
	Gender             string
}

func (q *Queries) UpdateSessionCabin(ctx context.Context, arg UpdateSessionCabinParams) (SessionCabin, error) {
	row := q.db.QueryRow(ctx, updateSessionCabin,
		arg.ID,
		arg.CampID,
		arg.SessionID,
		arg.CabinID,
		arg.GroupSize,
		arg.RequiredCounselors,
		arg.Gender,
	)
	var i SessionCabin
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.SessionAgeGroupID,
		&i.CabinID,
		&i.GroupSize,
		&i.RequiredCounselors,
		&i.Gender,
	)
	return i, err
}
