// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staleness.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSessionsByCamp = `-- name: ListSessionsByCamp :many
SELECT id
FROM sessions
WHERE camp_id = $1
`

func (q *Queries) ListSessionsByCamp(ctx context.Context, campID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByCamperEnrollment = `-- name: ListSessionsByCamperEnrollment :many
SELECT DISTINCT cse.session_id AS id
FROM camper_session_enrollments cse
WHERE cse.camp_id = $1 AND cse.camper_id = $2
`

type ListSessionsByCamperEnrollmentParams struct {
	CampID   pgtype.UUID
	CamperID pgtype.UUID
}

func (q *Queries) ListSessionsByCamperEnrollment(ctx context.Context, arg ListSessionsByCamperEnrollmentParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionsByCamperEnrollment, arg.CampID, arg.CamperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByCounselorRoster = `-- name: ListSessionsByCounselorRoster :many
SELECT DISTINCT sc.session_id AS id
FROM session_counselors sc
WHERE sc.camp_id = $1 AND sc.counselor_id = $2
`

type ListSessionsByCounselorRosterParams struct {
	CampID      pgtype.UUID
	CounselorID pgtype.UUID
}

func (q *Queries) ListSessionsByCounselorRoster(ctx context.Context, arg ListSessionsByCounselorRosterParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionsByCounselorRoster, arg.CampID, arg.CounselorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
