// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: time_slots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO time_slots (camp_id, time_slot_name)
VALUES ($1, $2)
RETURNING id, camp_id, time_slot_name, archived
`

type CreateTimeSlotParams struct {
	CampID       pgtype.UUID
	TimeSlotName string
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRow(ctx, createTimeSlot, arg.CampID, arg.TimeSlotName)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.TimeSlotName,
		&i.Archived,
	)
	return i, err
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :execrows
DELETE FROM time_slots
WHERE id = $1 AND camp_id = $2
`

type DeleteTimeSlotParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) DeleteTimeSlot(ctx context.Context, arg DeleteTimeSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimeSlot, arg.ID, arg.CampID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTimeSlot = `-- name: GetTimeSlot :one
SELECT id, camp_id, time_slot_name, archived
FROM time_slots
WHERE id = $1 AND camp_id = $2
`

type GetTimeSlotParams struct {
	ID     pgtype.UUID
	CampID pgtype.UUID
}

func (q *Queries) GetTimeSlot(ctx context.Context, arg GetTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRow(ctx, getTimeSlot, arg.ID, arg.CampID)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.TimeSlotName,
		&i.Archived,
	)
	return i, err
}

const listAllTimeSlots = `-- name: ListAllTimeSlots :many
SELECT id, camp_id, time_slot_name, archived
FROM time_slots
WHERE camp_id = $1
ORDER BY time_slot_name
`

func (q *Queries) ListAllTimeSlots(ctx context.Context, campID pgtype.UUID) ([]TimeSlot, error) {
	rows, err := q.db.Query(ctx, listAllTimeSlots, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.TimeSlotName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedTimeSlots = `-- name: ListArchivedTimeSlots :many
SELECT id, camp_id, time_slot_name, archived
FROM time_slots
WHERE camp_id = $1 AND archived = true
ORDER BY time_slot_name
`

func (q *Queries) ListArchivedTimeSlots(ctx context.Context, campID pgtype.UUID) ([]TimeSlot, error) {
	rows, err := q.db.Query(ctx, listArchivedTimeSlots, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.TimeSlotName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeSlots = `-- name: ListTimeSlots :many
SELECT id, camp_id, time_slot_name, archived
FROM time_slots
WHERE camp_id = $1 AND archived = false
ORDER BY time_slot_name
`

func (q *Queries) ListTimeSlots(ctx context.Context, campID pgtype.UUID) ([]TimeSlot, error) {
	rows, err := q.db.Query(ctx, listTimeSlots, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.TimeSlotName,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE time_slots
SET time_slot_name = $3
WHERE id = $1 AND camp_id = $2
RETURNING id, camp_id, time_slot_name, archived
`

type UpdateTimeSlotParams struct {
	ID           pgtype.UUID
	CampID       pgtype.UUID
	TimeSlotName string
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRow(ctx, updateTimeSlot, arg.ID, arg.CampID, arg.TimeSlotName)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.TimeSlotName,
		&i.Archived,
	)
	return i, err
}
